### ISSUE TITLE
Create new AND card tank temperature ><

### ISSUE THREAD

**Issue by severiti** [OlivierZal/com.melcloud#104]
Is it possible to create a new AND card that uses the tank temperature value  ? Looking to make a flow to increase the tank temperature if solar production is above xxx and tank temperature is below yyy

**Comment by OlivierZal** [comment]
Hi @severiti, such a card should exist… can you grant an access to olivier.zalmanski@me.com from the official MELCloud app so I can have a look?

Kind regards

**Comment by severiti** [comment]
sorry pretty new to this... can you tell me how ?

**Comment by OlivierZal** [comment]
To grant me an access, it’s under Settings > Guest access > Invite guest

To create a trigger or a condition, you need to create a « logic » card (greater or lower than, according to what you want) and apply it to the « hot water temperature » value. 

If you grant me an access I can provide screenshots.

**Comment by severiti** [comment]
Sorry @OlivierZal have resolved it with creating an own variable (when tank temperature decreases below xxx) 
Homey is pretty new to me

**Comment by OlivierZal** [comment]
You're welcome, it's exactly the way to do! And to hesitate to ask for any help.
