### ISSUE TITLE
Create AND card Zone 1/2 active

### ISSUE THREAD

**Issue by severiti** [OlivierZal/com.melcloud#105]
Would be great if you could create 2 cards

1. AND zone 1 is active
2. AND zone 2 is active

Looking to make a flow if zone 2 is not active then TADO radiotor should be switched to inactive as well

**Comment by OlivierZal** [comment]
Hi again @severiti, what do you call « zone is active »? Because heat pump operation modes depend on zones, but there is only one current operation is unique for the whole heat pump.

**Comment by severiti** [comment]
in the official Melcloud app you also can see if a zone is active (heating/cooling) (play icon) 
or inactive (pause icon)

**Comment by OlivierZal** [comment]
@severiti, can you provide me screenshots? To be honest I have an air-to-air heat pump and the only air-to-water users I know have only one zone 😊

So I would be grateful if you help me improve the multi zone behavior if possible!

**Comment by severiti** [comment]
![Screenshot 2023-03-13 205127](https://user-images.githubusercontent.com/65543685/224817741-34ca53da-089c-4b82-9670-8beebb45527f.png)

Sure, happy to help. Now playing with the app for 1-2 days and looks great !

**Comment by OlivierZal** [comment]
Ok, so it’s new for me! I know only one value in MELCloud API for the « current operation » (idle, etc.).

So I would definitively need a guest access to your MELCloud to see which values I can retrieve from the API in case of 2 zones (don’t worry, you won’t provide me any credentials by sharing me your devices).

**Comment by OlivierZal** [comment]
One naive question: does it happen you have different values in the zones, or is it always the same?

**Comment by severiti** [comment]
Guest access provided. 
yes most of the times you'll have different values in the zones

**Comment by OlivierZal** [comment]
Thanks a lot, I’ll have a look later this evening. In order to understand how it works, I could need to “play” a little with the settings… do you authorize me to do so? It would last only few seconds and I would revert back values immediately. It’s only to locate values in the MELCloud API.

**Comment by severiti** [comment]
ok ; let me know if anything is needed from my side.
if it helps : 
you might find 2 flow temperatures
1 for the flow in Zone 1 (in my case 34
1 for the flow in Zone 2 (in my case 33)
Would also be good to have these somehow in the homey app as i also want to make a flow based on solar production to increase the current value with xx

**Comment by OlivierZal** [comment]
The flow values were already known, current zone operations not. I’ll keep you updated.

**Comment by OlivierZal** [comment]
@severiti, here's the situation: I don't any "current operation for zone 2" value within your values:
```
{
    "EffectiveFlags": 0,
    "LocalIPAddress": null,
    "SetTemperatureZone1": 10,
    "SetTemperatureZone2": 18.5,
    "RoomTemperatureZone1": 22,
    "RoomTemperatureZone2": 20,
    "OperationMode": 0,
    "OperationModeZone1": 1,
    "OperationModeZone2": 1,
    "WeatherObservations": [
        {
            "Date": "2023-03-14T00:00:00",
            "Sunrise": "2023-03-14T06:56:00",
            "Sunset": "2023-03-14T18:41:00",
            "Condition": 176,
            "ID": 1097654911,
            "Humidity": 76,
            "Temperature": 10,
            "Icon": "wsymbol_0025_light_rain_showers_night",
            "ConditionName": "Pluie par endroits",
            "Day": 2,
            "WeatherType": 0
        },
        {
            "Date": "2023-03-14T03:00:00",
            "Sunrise": "2023-03-14T06:56:00",
            "Sunset": "2023-03-14T18:41:00",
            "Condition": 122,
            "ID": 1097654912,
            "Humidity": 81,
            "Temperature": 10,
            "Icon": "wsymbol_0004_black_low_cloud",
            "ConditionName": "Temps couvert",
            "Day": 1,
            "WeatherType": 2
        },
        {
            "Date": "2023-03-14T15:00:00",
            "Sunrise": "2023-03-14T06:56:00",
            "Sunset": "2023-03-14T18:41:00",
            "Condition": 122,
            "ID": 1097654916,
            "Humidity": 55,
            "Temperature": 7,
            "Icon": "wsymbol_0004_black_low_cloud",
            "ConditionName": "Temps couvert",
            "Day": 2,
            "WeatherType": 1
        },
        {
            "Date": "2023-03-15T03:00:00",
            "Sunrise": "2023-03-15T06:53:00",
            "Sunset": "2023-03-15T18:43:00",
            "Condition": 113,
            "ID": 1098741528,
            "Humidity": 86,
            "Temperature": 1,
            "Icon": "wsymbol_0008_clear_sky_night",
            "ConditionName": "Dégagé/Ensoleillé",
            "Day": 2,
            "WeatherType": 2
        }
    ],
    "ErrorMessage": null,
    "ErrorCode": 8000,
    "SetHeatFlowTemperatureZone1": 33,
    "SetHeatFlowTemperatureZone2": 33,
    "SetCoolFlowTemperatureZone1": 20,
    "SetCoolFlowTemperatureZone2": 20,
    "HCControlType": 1,
    "TankWaterTemperature": 44,
    "SetTankWaterTemperature": 47,
    "ForcedHotWaterMode": false,
    "UnitStatus": 0,
    "OutdoorTemperature": 12,
    "EcoHotWater": true,
    "Zone1Name": null,
    "Zone2Name": null,
    "HolidayMode": false,
    "ProhibitZone1": false,
    "ProhibitZone2": false,
    "ProhibitHotWater": true,
    "TemperatureIncrementOverride": 0,
    "IdleZone1": true,
    "IdleZone2": true,
    "DemandPercentage": 100,
    "DeviceID": 51635659,
    "DeviceType": 1,
    "LastCommunication": "2023-03-13T22:29:40.8",
    "NextCommunication": "2023-03-13T22:30:40.8",
    "Power": true,
    "HasPendingCommand": false,
    "Offline": false,
    "Scene": null,
    "SceneOwner": null
}
```

I see only the value I already knew, that is `OperationMode: 0`, which means `Idle`, but as you can see the zone is not specified, contrary to `OperationModeZone1` and `OperationModeZone2`, which is the mode you can set under your unit settings (`Heat` / `Cool`, `Room`, `Flow`, `Curve`).

However I have a theory: maybe `OperationMode` common except for `idle, whose values could specific under `IdleZone1` and `IdleZone2`, but I need to confirm when I see 2 different values for each zone.

I'll keep you updated when it's confirmed.

**Comment by OlivierZal** [comment]
But maybe you could confirm my theory: can you have zone 1 different from idle and zone 2 also different from idle but with another value than zone 1 (for example: zone 1 = heating and zone 2 = legionella) ?

**Comment by severiti** [comment]
Hi, yes this is possible.
Zone 1 can be heating/cooling ; while zone 2 is idle (each zone can play or pause)
Zone 1 can even be using a "curve" ; while zone 2 is using "flow"

**Comment by OlivierZal** [comment]
That's not exactly what I meant but don't worry I'll handle :-)

**Comment by OlivierZal** [comment]
@severiti, do you thing you are able to make zones have different statuses so I can see the corresponding API values?

**Comment by severiti** [comment]
@OlivierZal if you look between 2pm CET and 4.30pm CET that will be the case

**Comment by OlivierZal** [comment]
@severiti, as you can see: currently zone 1 is "idle" and zone 2 is "heating", but in the console both zones are marked "idle"...

<img width="2240" alt="Capture d’écran 2023-03-14 à 13 48 09" src="https://user-images.githubusercontent.com/88216225/225006051-bd0ded0f-804b-4c68-b19b-820e712869cb.png">

**Comment by OlivierZal** [comment]
@severiti, I don't understand how it works but finally it can be related to `IdleZone1` and `IdleZone2` (see attached screenshot).

I have another question: I see that sometimes "Hot Water" has a "Prohibit" status.
Is that something you configure or something automatically handled by the system?

<img width="2240" alt="Capture d’écran 2023-03-14 à 15 06 57" src="https://user-images.githubusercontent.com/88216225/225028335-b18c6657-e94a-4a90-b7ee-cd8a95d18330.png">

**Comment by severiti** [comment]
ok that sounds good !
Hot water is prohibit because I have programmed it to only be active in a certain timeslot it's a setting in the heatpump

**Comment by OlivierZal** [comment]
Oh ok, I guess you can do the same for every zone (`ProhibitZone1` and `ProhibitZone2` in the screenshot).

**Comment by severiti** [comment]
Normally there are max 2 zones ; so yes that would work i believe

**Comment by OlivierZal** [comment]
@severiti, could look like:

![IMG_2422](https://user-images.githubusercontent.com/88216225/225079255-91107d6f-0ff8-4c92-9f1a-3be6ad2369fe.PNG)
![IMG_2423](https://user-images.githubusercontent.com/88216225/225079303-5d2b0345-3825-4341-8730-cf4c5f1303fe.PNG)
![IMG_2424](https://user-images.githubusercontent.com/88216225/225079350-45ad4542-5621-475b-9c6d-5136c7a0cff8.PNG)

**Comment by severiti** [comment]
looks okay to me...

**Comment by OlivierZal** [comment]
@severiti, I've almost finish the new version of the app, but have some more tests to perform before to release (I've just seen you removed the access while I was testing).

Would you be ok to grant me an access for one more day?

**Comment by OlivierZal** [comment]
I've created a test version: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

**Comment by OlivierZal** [comment]
Hi @severiti, could you please provide me again (temporarily) a guest access for test purposes?

You're the only one I know with both a 2-zone and can-cool device...

**Comment by OlivierZal** [comment]
Hi Tim, I succeeded to test with a workaround. 

Thanks 😊

**Comment by OlivierZal** [comment]
Hi @severiti,

Could it be possible to grant guest access again to olivier.zalmanski@me.com from the official MELCloud app? I would need to check something for 2-zone devices. 

Thanks in advance!

**Comment by severiti** [comment]
should be ok now ;

Op di 28 nov 2023 om 07:06 schreef Olivier Zalmanski <
***@***.***>:

**Comment by OlivierZal** [comment]
Thanks @severiti, I remove the access since I'm done.

**Comment by severiti** [comment]
Ok that's great.

Other question... In the heatpump there is a possibility to set a "silent
mode" ; I can't see it in the native melcloud app ; but can you investigate
if you can show this in homey ?
Would be great to have this automation as I use it to limit the power of my
machine.

Op di 28 nov 2023 om 10:58 schreef Olivier Zalmanski <
***@***.***>:

**Comment by OlivierZal** [comment]
Hi @severiti, unfortunately this function is not available from the MELCloud API :-(

**Comment by OlivierZal** [comment]
Hi @severiti, would it be possible to provide olivier.zalmanski@me.com with a guest access again? I would need an access to 2-zone products for some new features.

**Comment by severiti** [comment]
ok , should be fixed now

Op do 28 nov 2024 om 09:50 schreef Olivier Zalmanski <
***@***.***>:

**Comment by OlivierZal** [comment]
![image](https://github.com/user-attachments/assets/4690833c-e218-4b91-8829-4847586c9d2e)

![image](https://github.com/user-attachments/assets/3ef5bcf5-d84b-48b4-b605-0d892c7584fd)

In progress, I need to find a way to have it well displayed for your type of device.

**Comment by OlivierZal** [comment]
@severiti, I'm almost done with the code. Quick question, do you finally activated "THW10" (https://github.com/OlivierZal/com.melcloud/issues/114)? If so, I would need only one-day access so I can check something.

**Comment by severiti** [comment]
Hi Olivier,

No, never did that.

Regards,
Tim

Op wo 4 dec 2024 om 13:47 schreef Olivier Zalmanski <
***@***.***>:

**Comment by OlivierZal** [comment]
I'm almost done with the new features, would you agree to grant me again an access to your device 2 more days so I can test the behavior on 2-zone devices? Thanks

**Comment by OlivierZal** [comment]
@severiti, I'm almost done with new features' development, would you agree to grant me again an access to your device for 2 more days, so I can test the behavior on 2-zone devices? Thanks
