### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by francisrath** [OlivierZal/com.melcloud#109]
I just set up my new air-to-air unit in the MELCloud app on my phone.

Then I tried to add it to Homey, but when I log in it says no units were found.

I also tried to go to settings of your app and log in there. Then I get "Request failed with status code 403". Any ideas?

**Comment by OlivierZal** [comment]
Hi @francisrath, there is a known problem which does not depend on MELCloud Homey app...

Users having the same issue succeeded in adding the device from the Homey web app: https://my.homey.app/homeys/61d577a12535640bc3b0cb19/devices ("+" button on the top-right).

Could you please try this way?

**Comment by OlivierZal** [comment]
@francisrath, I translated the app into Norwegian last week by the way 😄

**Comment by francisrath** [comment]
It worked in the browser on my PC. Strange - but thanks :) 

I'll check out the Norwegian translations also :)

**Comment by OlivierZal** [comment]
You're welcome ☺️
