### ISSUE TITLE
Can’t add new Air to Water HP in 306

### ISSUE THREAD

**Issue by MTRKhn** [OlivierZal/com.melcloud#11]
I deleted the device in Homey and wanted to recreate. After login in MELCloud, no device are available.

**Comment by OlivierZal** [comment]
Hi @MTRKhn, if I well understand you don't see your device in MELCloud anymore?
Seems rather to be a MELCloud issue than an Homey one, maybe related to a bad guest access handling.
I've removed my guest access to avoid any conflict (even if it was a read-only access): I think you should add your device again to your MELCloud account.
Don't hesitate to contact me if you have any to pair your device again in Homey afterwards.

**Comment by MTRKhn** [comment]
I still have my device in MELCloud, but I can’t add it again in Homey.

![BF0EFC94-9076-40FA-A362-5226141BE40E](https://user-images.githubusercontent.com/72077818/193352112-df37a9d9-ec86-47c6-9478-05009674cf9a.jpeg)

i’m pretty sure I did it in either 305 or 304

**Comment by OlivierZal** [comment]
Oh, you're French ;-)

Would you mind to provide me a read-only guest access again, so I can see if I succeed in adding it?

**Comment by MTRKhn** [comment]
Nobody is perfect 🤪

Access will be granted in a few minutes.

**Comment by OlivierZal** [comment]
![IMG_1634 2](https://user-images.githubusercontent.com/88216225/193355178-065b7f6f-7d96-416a-adec-71eba61a0f84.PNG)

**Comment by OlivierZal** [comment]
Théoriquement, si vous n'arrivez pas à ajouter un appareil, c'est qu'il est déjà sur votre Homey.
Arrivez-vous à accéder à cette page https://tools.developer.homey.app/tools/devices et si oui, est-ce que par hasard vous y voyez d'une façon ou d'une autre votre appareil ?

**Comment by OlivierZal** [comment]
Est-ce que ce ne serait pas une manipulation malheureuse, comme par exemple l'avoir supprimé seulement des favoris, mais pas de vos appareils ?
En l'ajoutant à nouveau aujourd'hui, ne vous-êtes vous pas trompé de pièce en l'associant ? ou ne se trouve-t-il pas dans la "pièce par défaut" ?

Désolé, je lance des idées peut-être un peu bête comme ça, car n'arrivant pas à reproduire...

**Comment by MTRKhn** [comment]
En effet, il est déjà enregistré, mais jusqu'à il y a quelques minutes, j'avais bien les deux enregistrés (un avec la 302 stable et un avec la dev/test 306). Bizarre, je viens de dégager l'autre et maintenant j'arrive à le rajouter. Là j'avoue, il y a un peu de magie :-D

**Comment by OlivierZal** [comment]
Alors j'ai déjà constaté que parfois, après l'installation d'une nouvelle version, il faut un peu de temps pour que la nouvelle version prenne le dessus (et un utilisateur que j'ai débuggé l'a aussi expérimenté aujourd'hui même).

**Comment by OlivierZal** [comment]
C'est aussi dû au fait que la version 3.0.6 gèrent les devices de la même façon que la 2.0.12, si bien qu'ils ne peuvent plus être dupliqués, contrairement à la version 3.0.2, qui les géraient différemment.

Avec la 3.0.6 j'interdis une pompe air-air d'être enregistrée comme air-eau et vice-versa, ce qui n'était pas le cas auparavant.
