### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by ikhilko** [OlivierZal/com.melcloud#140]
After the latest release 17.0.3, the app stopped working. I cannot control my air-condition from Homey. It just do nothing in melcloud.
@ozalmanski can you help me?

**Comment by OlivierZal** [comment]
Hi @ikhilko, I’ll work on it asap.

**Comment by OlivierZal** [comment]
It’s an issue from MELCloud, I guess they have a certificate which expired, so I’ll deploy a workaround by disabling SSL verification (what is not safe but I have no choice…). 

I’ll keep you updated.

**Comment by ikhilko** [comment]
Thank you! Now it is working. Thank you for so fast fix 💨

**Comment by janhjordie** [comment]
Yeah, I have same issue. But it works with the test version 👌
![image](https://github.com/OlivierZal/com.melcloud/assets/79910/d9cf9933-1847-48e6-bfac-6a453d5437eb)

**Comment by OlivierZal** [comment]
Now the workaround is available for anyone.
