### ISSUE TITLE
Event triggered for multiply types at the same time

### ISSUE THREAD

**Issue by janhjordie** [OlivierZal/com.melcloud#15]
Hey @OlivierZal 
If I use the Operation Mode has changed card, and make two separate cards, with DHW Heating and Heating. They are both triggered at the same time. The trigger is triggered every time the MELCloud is polling the heatpump.

![Homey_Pro](https://user-images.githubusercontent.com/79910/193413719-ddce0a0c-7415-4bf5-87c1-cc7abe91773d.jpg)
![image](https://user-images.githubusercontent.com/79910/193413828-18bc85d4-8e00-454e-8649-e585dc77b050.png)

**Comment by janhjordie** [comment]
![image](https://user-images.githubusercontent.com/79910/193413869-6aaf31be-2e03-49dc-8f9b-d2cda31cb9b0.png)

**Comment by OlivierZal** [comment]
Hi @janhjordie, I’ll have a look. I think it will easy to find the issue, otherwise maybe I’ll ask you for a guest access again so I can test. I’ll keep you updated.

**Comment by OlivierZal** [comment]
By the way I will release a new test version soon since I found a use case where flow does not update.

**Comment by janhjordie** [comment]
@OlivierZal you have guest access again 😄

**Comment by OlivierZal** [comment]
Thanks! I've located many bugs I've "theoretically" fixed, so it will help.

**Comment by OlivierZal** [comment]
Hi @janhjordie!

Thank you very much for your support ;-)

Could you please install https://homey.app/a/com.mecloud/test/ and tell me if it solved your issues?

Best regards

**Comment by janhjordie** [comment]
I have just installed it. I will return asap 😜

**Comment by janhjordie** [comment]
The zone operation mode is broken again. 
When i set it to flow its set to room

**Comment by OlivierZal** [comment]
Oh, the settings is well changed but this is the opposite value which is sent to MELCloud.

Investigating further...

**Comment by janhjordie** [comment]
I have installed 3.1.1. Testing 😜

**Comment by OlivierZal** [comment]
Ok, I understand sometimes it works and sometimes not: there is a small delay after settings being saved, I added a sleep of 5 seconds and it seems to work.

Here is the new version to install: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

**Comment by janhjordie** [comment]
The zone operation works again. 
But the outside temp variable is now missing

**Comment by OlivierZal** [comment]
@Johan1984S, @FrodeAlm, @MTRKhn, @smurfb, @doinkmaster, @Deejaybaze, @FridhF, FYI

**Comment by janhjordie** [comment]
And can see the frequency has changed name to Heat Pump Frequency. 
Please be carefull changing variables, because it breaks flows

**Comment by OlivierZal** [comment]
Now I use the same names than the MELCloud API to avoid any confusion, that's why I changed labels. I left the ids to avoid breaking the flow cards.

**Comment by OlivierZal** [comment]
Now I use the same names than the MELCloud API to avoid any confusion, that's why I changed labels. I left the ids to avoid breaking the flow cards (outside => outdoor, etc.).

**Comment by OlivierZal** [comment]
@janhjordie, can you try this new version?

**Comment by janhjordie** [comment]
3.1.2 👍 
Now it works again. 

![image](https://user-images.githubusercontent.com/79910/194094755-99b5c124-e3e8-4d08-80d9-bdc89c98c27c.png)

**Comment by janhjordie** [comment]
But I can't read the Outdoor Temperature from the flows. The variable does not exists

**Comment by OlivierZal** [comment]
Have you a screenshot of your flow and of the error message?

**Comment by OlivierZal** [comment]
<img width="400" alt="Capture d’écran 2022-10-05 à 17 13 30" src="https://user-images.githubusercontent.com/88216225/194096852-765cfadb-2950-4a74-93fa-bf28965529b5.png">

**Comment by OlivierZal** [comment]
I can roll-back the names without any problem, it's just that are very different from the API, so it's very disturbing when trying to understand the code.

**Comment by OlivierZal** [comment]
Trying to reproduce.

**Comment by OlivierZal** [comment]
Is it possible that your browser use a cache keeping a previous version? Can you clear the cache of your browser?

**Comment by OlivierZal** [comment]
My board indicates that currently nobody has 3.1.2 installed.

<img width="1829" alt="Capture d’écran 2022-10-05 à 17 21 59" src="https://user-images.githubusercontent.com/88216225/194098688-d2376c0f-bc21-470a-b478-8a6804d6ac75.png">

**Comment by janhjordie** [comment]
Cache is cleared, also tried in private browsing, and another browser. Same issue.

My Homey says 3.1.2 

![image](https://user-images.githubusercontent.com/79910/194098951-d8a96001-8d7c-4f06-bc31-ac33d8969e16.png)

**Comment by janhjordie** [comment]
I have to leave in 10 min. And will be back later tonight 22'ish to test.
Maybe you could try bump up the version

**Comment by OlivierZal** [comment]
I'll try something.

**Comment by OlivierZal** [comment]
I'll roll-back some names...

**Comment by OlivierZal** [comment]
But without finding the root cause and not reproducing, I'm not sure it would solve your issue.
Can you install production version and then install experimental again?

**Comment by MTRKhn** [comment]
> I'll roll-back some names...

Are you changing names again ? I just changed all my Grafana dashboards :'(

**Comment by OlivierZal** [comment]
@MTRKhn, I can wait for @janhjordie's feedback but if I don't find the root cause, there's a risk it happens for other users...

My version was a test, and I confess that many Homey behaviours are still obscure to me...

Are you flows working well? Do you succeed in accessing the new capabilities?

**Comment by OlivierZal** [comment]
Maybe wait for tomorrow for additional configurations, since the test has not been transformed yet...

**Comment by FrodeAlm** [comment]
Water temp shows 25 degrees all the time, but all other values ​​now work well.Med hilsen Frode AlmMob: +47917176305. okt. 2022 kl. 18:05 skrev Olivier Zalmanski ***@***.***>:﻿
@MTRKhn, I can wait for @janhjordie's feedback but if I don't find the root cause, there's a risk it happens for other users...
My version was a test, and I confess that many Homey behaviours are still obscure to me...
Are you flows working well? Do you succeed in accessing the new capabilities?

**Comment by OlivierZal** [comment]
Hi here, I cannot reproduce @janhjordie's issue, so it's probably safer to roll-back capability names.

**Comment by Deejaybaze** [comment]
Hi. On my end it seems to work well now. Just one question. The "Flow Temperature" Is that the output pipe for zone 1? And can i via the app set mode to Flow, and set the output temperature to xx (25)?

**Comment by OlivierZal** [comment]
Hi @Deejaybaze, yes for the flow temperature. 

You can set flow mode and set target & other settings from the device's settings (wheel on the top right).

**Comment by Deejaybaze** [comment]
And all is for zone 1?

**Comment by OlivierZal** [comment]
When you pair your device for the first time, you are proposed 1 device for zone 1 and 1 device for zone 2 if zone 2 is configured, so zone control depends on 2 different devices. If you added a zone 2, I guess you need to pair your device again to see specific device for zone 2.

**Comment by Deejaybaze** [comment]
Ahh.. Thank you. I have not installed zone 2 yet. But will soon.
Thank you.

**Comment by janhjordie** [comment]
@OlivierZal It worked installing 3.0.6 and then 3.1.2 again !
Now I have the Outdoor temperature 🚀 
That was a nice workaround !

**Comment by janhjordie** [comment]
@OlivierZal It seems the Operation Mode Cards not working. I don't get any triggers on change to DWH or Heating (the only ones I use)

![image](https://user-images.githubusercontent.com/79910/194235253-a872f07f-084e-4a3d-b85e-0969ab5bd7d7.png)

**Comment by OlivierZal** [comment]
Here is a new version: https://homey.app/a/com.mecloud/test/

Value modification seems to fixed, even if something there is some lag on MELCloud UI's side.
I didn't test all the flows yet.

**Comment by OlivierZal** [comment]
Note: to enhance sync and triggering I moved transformed some settings into capabilities

**Comment by OlivierZal** [comment]
Here is a new test version of the app: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

Don't hesitate to raise any issue you encounter.

**Comment by OlivierZal** [comment]
Production version with the fixes should be available in a couple of days, don’t hesitate to raise an issue in case of any bug or unexpected behavior.
