### ISSUE TITLE
Temperature reverts back and can I retriev the current indoor temp from the indoor sensor?

### ISSUE THREAD

**Issue by Johan1984S** [OlivierZal/com.melcloud#16]
Hi,

Just got a new Mitsubishi heatpump installad (Air to water), I have also an wireless indoor controller(that provides current indoor temp to the main unit) installed. However I'm facing two issues, cant I retrieve the current indoor temperature to an advanced flow?  Second problem is that the unit reverts back to the original temperature if I have flow setting it to 19 it will revert back to original value after a few minutes.

**Comment by OlivierZal** [comment]
Hi @Johan1984S, I'm the new developer of the project, and I found bugs that I fixed in this test version: https://homey.app/a/com.mecloud/test/

Could you please tell me if it solves your issue?

Best regards

**Comment by OlivierZal** [comment]
Here is a new version: https://homey.app/a/com.mecloud/test/

Value modification seems to fixed, even if something there is some lag on MELCloud UI's side.
I didn't test all the flows yet.

Note: to enhance sync and triggering I moved transformed some settings into capabilities

**Comment by OlivierZal** [comment]
Here is a new test version of the app: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

Don't hesitate to raise any issue you encounter.

**Comment by OlivierZal** [comment]
Production version with the fixes should be available in a couple of days, don’t hesitate to raise an issue in case of any bug or unexpected behavior.

**Comment by Johan1984S** [comment]
Big thanks, seems to work very well know!
