### ISSUE TITLE
New experimental app 3.1.2 ( ecodan )

### ISSUE THREAD

**Issue by ronennieshow** [OlivierZal/com.melcloud#18]
Hi 

I have been update'ted to the newest version

And now there are some issues back

I can not start forced hot water to on from homey to the mel cloud app
I can nog change the temperatur from te melcloud back to the homey app.
If i change the temperatur in homey it is taken over by the melcloud app

![image](https://user-images.githubusercontent.com/113858484/194153442-f4e4a3cc-a4db-429d-96ca-6ceff34074a3.png)

![image](https://user-images.githubusercontent.com/113858484/194153498-ed500206-defb-4fe6-ae4b-3a487d64ccba.png)

![image](https://user-images.githubusercontent.com/113858484/194153554-9963c750-95e6-44c3-9f51-291cff9c3cbc.png)

**Comment by OlivierZal** [comment]
Hi @ronennieshow, I’ll have a look ASAP.

**Comment by OlivierZal** [comment]
I made some modification of the code today but need to be home (tonight) so I can test.

**Comment by OlivierZal** [comment]
@ronennieshow and @janhjordie,

Here is a new version: https://homey.app/a/com.mecloud/test/

Value modification seems to fixed, even if something there is some lag on MELCloud UI's side.
I didn't test all the flows yet.

**Comment by OlivierZal** [comment]
Note: to enhance sync and triggering I moved transformed some settings into capabilities

**Comment by janhjordie** [comment]
@OlivierZal 
I just tried to change the hot water temperature with the 3.1.3

Doing it from the heatpump property page works just fine
![image](https://user-images.githubusercontent.com/79910/194474964-90a6e148-611f-4d27-964a-b1f88763f2ff.png)

But doing the same thing from a card does not work

![image](https://user-images.githubusercontent.com/79910/194475235-71d43672-f455-40e1-bce9-98a1c4591038.png)

**Comment by OlivierZal** [comment]
On it, @janhjordie.

**Comment by ronennieshow** [comment]
If i change the room setpointtemperatur in a flow in homey it is not taken over by the mel cloud app
If i change the room setpoint temperatur in mel cloud it is taken over by homey

**Comment by OlivierZal** [comment]
@ronennieshow, can I have a screenshot of your flow so I can reproduce?

What is strange is that setpointtemperature is a standard capability, then not handled by the app code but directly by Homey system.

**Comment by OlivierZal** [comment]
@janhjordie, the issue has been located and fix for the next test version.

How do you set the "eco hot water" setting? Via MELCloud website?

**Comment by janhjordie** [comment]
@OlivierZal Sounds great !
I have never set the eco hot water from Homey. And can't find any options on the Native MELCloud to set it

**Comment by OlivierZal** [comment]
@janhjordie, for your MELCloud general culture, MELCloud needs a binary flag for each setting we send hi.
From a website, we can inspect the elements and see which flags is used to change Eco Hot Water (for example), so without website I need to write a script and test recursive binaries until it works.

**Comment by janhjordie** [comment]
@OlivierZal You are welcome to use my MELCloud to test.

**Comment by OlivierZal** [comment]
Unless... @ronennieshow, do you have 1 or 2 zones configured with your Ecodan?

**Comment by janhjordie** [comment]
@OlivierZal 
Setting the temp works for me, but it's also turn off the heatpump. Totally wierd

![image](https://user-images.githubusercontent.com/79910/194542308-a58b4323-a6d8-4140-9f4f-36d4cfc31b74.png)

**Comment by OlivierZal** [comment]
Maybe our tests interfere one with the other. I'll stop them right now, can you please try once again?

**Comment by janhjordie** [comment]
@OlivierZal Haha, I think you are right 🤣 It works just fine setting the hot water temperature, and does not turn if off !

Btw, be aware of polling to often from MELCloud. They changed to MQTT for some months ago, so if you poll it to often, the message queue can handle the messages.

I found that polling faster than 3 minutes made the MELCloud unresponsible.

**Comment by OlivierZal** [comment]
Here is a new test version of the app: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

Don't hesitate to raise any issue you encounter.

**Comment by janhjordie** [comment]
Hey @OlivierZal 
I just installed 3.1.5. The set hot water temp and force mode is working just fine.

But the event trigger on operation mode does not work. Ex. when the operation mode changes to DHW, nothing happens.

![image](https://user-images.githubusercontent.com/79910/194693357-b677138c-9740-4c3e-9bcd-25fabb507abb.png)

**Comment by OlivierZal** [comment]
On it! (after my daughter dance's lesson).

**Comment by janhjordie** [comment]
@OlivierZal  Enjoy the time with your daughter. That's also very important. And much more than this issue 😉

**Comment by OlivierZal** [comment]
@janhjordie, I cannot reproduce

![image](https://user-images.githubusercontent.com/88216225/194721743-b823b651-e5c0-481d-8ec7-7b4aa6bc9e95.png)
![image](https://user-images.githubusercontent.com/88216225/194721762-7f459125-6f09-418f-b6a1-042f51fb1649.png)
![image](https://user-images.githubusercontent.com/88216225/194721766-df3ce4a6-7ff9-48e1-9772-4ea1fb464961.jpeg)

**Comment by janhjordie** [comment]
I will try uninstalling and install prod version, and then 3.1.5 again. 
Maybe that will help. I'll return

**Comment by OlivierZal** [comment]
And create a new flow from scratch.

**Comment by OlivierZal** [comment]
@janhjordie, I’ve just been notified again 😉

![356BF85D-1819-4C1F-B4A5-9F14DF3969A6](https://user-images.githubusercontent.com/88216225/194725975-a121e159-bcb2-403e-97a4-128459536b5d.jpeg)

**Comment by OlivierZal** [comment]
Production version with the fixes should be available in a couple of days, don’t hesitate to raise an issue in case of any bug or unexpected behavior.
