### ISSUE TITLE
Cannot logon

### ISSUE THREAD

**Issue by Berrywaanders1** [OlivierZal/com.melcloud#185]
Hello!

I just installed the MELCloud app since we got 5 Mitsubishi Airco’s. When I add a new airco air-air it says no new device found. 

When I click on the diagnostic button in settings it says 401. Rebooted the homey and removed and reinstalled the app without any luck. 

Can someone guide me in the right direction?

kind regards Berry.

**Comment by OlivierZal** [comment]
Hi @Berrywaanders1! Do you succeed to add the device from this page? https://my.homey.app/ (+ button on the top right)

**Comment by Berrywaanders1** [comment]
Whoops, that works indeed!

Thank you Olivier!

Met hartelijke groet,

Berry Waanders.

M: 0626424243 E: ***@***.***

[cid:12dbd52c-f1e4-4e18-a2e6-de06ee697346]

________________________________
Van: Olivier Zalmanski ***@***.***>
Verzonden: woensdag 6 september 2023 20:28
Aan: OlivierZal/com.melcloud ***@***.***>
CC: Berry Waanders | Centrum voor IT ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [OlivierZal/com.melcloud] Cannot logon (Issue #185)


Hi @Berrywaanders1<https://github.com/Berrywaanders1>! Do you succeed to add the device from this page? https://my.homey.app/ (+ button on the top right)
