### ISSUE TITLE
Movinh from Homey 2019 to Homey 2023

### ISSUE THREAD

**Issue by paxus42** [OlivierZal/com.melcloud#186]
Hi,

I'm trying to move to the new Homey from my old. I've uninstalled the Melcloud app on the old one but when I'm trying to add my air-air heater on the new one I only get that there is no new devices, please advise.

Pål

**Comment by OlivierZal** [comment]
Hi @paxus,

Do you succeed to add the device from this page? https://my.homey.app/ (+ button on the top right)

More and more users report me this mobile app issue. Do you run on Android or iOS?

**Comment by OlivierZal** [comment]
Hi @paxus42,

Do you succeed to add the device from this page? https://my.homey.app/ (+ button on the top right)

More and more users report me this mobile app issue. Do you run on Android or iOS?

**Comment by OlivierZal** [comment]
Also I would be grateful if you can try again from the mobile and send me a "report", so I can see if I can do something.

**Comment by paxus42** [comment]
I did do it by the web before I got your latest message and it worked.

**Comment by OlivierZal** [comment]
Good to hear it worked 😊

Never mind if you've already added your devices: trying to add devices even if all have been added will generate an API call which will be printed in the report and would help me.
