### ISSUE TITLE
Devices stopped to work in 21.1.0

### ISSUE THREAD

**Issue by ikhilko** [OlivierZal/com.melcloud#187]
The app just broken in the latest 21.1.0 release. Diagnostic record: f647dc3b-7a90-4a05-97bb-c31060f3e605

**Comment by logchem** [comment]
Same for me. In the 21.1.0 release the flows has errors and for that reason the cooling temp was set to 5 degrees celsius.

**Comment by OlivierZal** [comment]
Hi @ikhilko and @logchem, should be fixed with 21.1.1. Can you please confirm? Sorry for the inconvenience :-(

**Comment by OlivierZal** [comment]
@logchem, here it is: https://homey.app/fr-fr/app/com.mecloud/MELCloud/

**Comment by logchem** [comment]
Just tested everything and it looks like everything is working again in release 21.1.1 :)
