### ISSUE TITLE
Issue MelCloud

### ISSUE THREAD

**Issue by stefthu** [OlivierZal/com.melcloud#215]
Dear Develloper, Impossible to find my Air-Air Mitsubishi on Homey already connected to MelCloud. Login is correct but meessage "No device found"
Could you help me
Thanks
Stéphane

**Comment by OlivierZal** [comment]
Hi @stefthu, unfortunately there is an issue on Homey side which make Android app timeout too soon…

The only way I know is to add the device from the Homey web app: https://my.homey.app (top-right "add devices"). 

Can you please confirm it works?

Kind regards

**Comment by stefthu** [comment]
Hi Olivier,

Thanks for your suppot, Yes from the web app it’s working

Many Thanks

Stéphane

De : Olivier Zalmanski ***@***.***
Envoyé : mardi 24 octobre 2023 21:11
À : OlivierZal/com.melcloud ***@***.***>
Cc : stephane THURIER ***@***.***>; Mention ***@***.***>
Objet : Re: [OlivierZal/com.melcloud] Issue MelCloud (Issue #215)


Hi @stefthu<https://github.com/stefthu>, unfortunately there is an issue on Homey side which make Android app timeout too soon…

The only way I know is to add the device from the Homey web app: https://my.homey.app (top-right "add devices").

Can you please confirm it works?

Kind regards
