### ISSUE TITLE
Feature request - Separate COP values

### ISSUE THREAD

**Issue by janhjordie** [OlivierZal/com.melcloud#22]
Hey @OlivierZal 
In your new version 4.0 you added the power consumption, production and COP value. 
In the native MELCloud app you are able to get consumption, production and COP, for hot water and heating production. 
That could be a very nice feature. 
So the two individual values and the average total as we have now

Thanks 🙏

**Comment by OlivierZal** [comment]
Hi @janhjordie, I've already did so (+ decimals asked in other comments). Tests are ongoing, I'll post a new test release soon.

**Comment by janhjordie** [comment]
Ohh, fantastic 👌🤘
