### ISSUE TITLE
App stop reading/setting values

### ISSUE THREAD

**Issue by ChristerSjo** [OlivierZal/com.melcloud#234]
Since 12 a clock today (14 Nov 2023) MelCloud app stopp reading values and can’t set values. The MelCloud app from Mitsubishi can read and set values.

Have restarted Homey and restarted the Ecodan Air/Water heatpump but no success.

**Comment by severiti** [comment]
Same issue here, looks like Mitsubishi has changed something at their side…

**Comment by OlivierZal** [comment]
Hi @severiti and @ChristerSjo, indeed this is a global MELCloud issue, as explained [here](https://community.homey.app/t/app-pro-melcloud/73094/63?u=olivierzal)

The solution to log in again (device settings > maintenance) worked for many users.
