### ISSUE TITLE
Can't add Melcloud device

### ISSUE THREAD

**Issue by Grevling73** [OlivierZal/com.melcloud#24]
When trying to add air to air heatpump I get error message: "this.getName is not a function"

Error occurres after entering Melcloud Account info.

Any ideas?

Thanks
Leif

**Comment by OlivierZal** [comment]
Hi @Grevling73, such an error message occurs when there is a problem with credentials or no device can be found.

**Comment by Grevling73** [comment]
Hi,
No, the MelCoud app works fine.

Leif

**Comment by OlivierZal** [comment]
Sorry @Grevling73, just to be sure to understand, did you succeed in adding your device by downloading the link I gave you in my previous comment, or do you still have an issue?

If you have still an issue, you can go to your official MELCloud and invite olivier.zalmanski@me.com as a guest – I don't need full access to investigate, just a restricted (read-only) access.

**Comment by OlivierZal** [comment]
@Grevling73 

Thanks to your invite I understand what happens: your type of device is not supported yet by the Homey app... but thanks to you I can add it!

I need to do some research to see which APIs I need to call to give you the control. Which model do you have? Is it a Energy-Recovery-Ventilation?

**Comment by Grevling73** [comment]
Hello,

This is an air to air heatpump.
I will enclose a photo of the model info.

Leif

**Comment by OlivierZal** [comment]
Oh ok, no need to send me info, I have an idea. I'll make some test and come back to you.

**Comment by OlivierZal** [comment]
@Grevling73, now I can see your device (see attached screenshot). Can you please try again?

![image](https://user-images.githubusercontent.com/88216225/196797893-a20985e3-d4f8-40d5-a689-9e2da9e267c9.png)

**Comment by Grevling73** [comment]
Unfortunately still the same. "No new units have been found". See attached screenshot.

Leif

**Comment by OlivierZal** [comment]
@Grevling73, maybe a last try: I don't why but sometimes multi-floor can make the device search fail.
Can you move your device on the other floor and try again?

**Comment by OlivierZal** [comment]
Another idea: maybe your app crashed or something but the device has been registered in Homey despite all.

Can you please send me a screenshot of all your Homey devices?

**Comment by Grevling73** [comment]
Hello again,
I now managed to add the heatpump via pc. Could be a bug with the Android phone app?

Leif

**Comment by OlivierZal** [comment]
I changed the request library and the way we get the list, I hope this will solve the issue.
