### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bfisk** [OlivierZal/com.melcloud#242]
Hello
Have been using MELCloud with Homey Pro 19 and two air to air heat pumps, no issues for about two years now. 
Yesterday it stopped responding from Homey. The OEM app works fine and the units are responding and online, but no communication to/from Homey. 
Homey gives no errors.
Have tried restarting the Homey app but to no avail.

**Comment by OlivierZal** [comment]
Hi @bfisk,

Indeed there is a global MELCloud issue, as explained [here](https://community.homey.app/t/app-pro-melcloud/73094/63?u=olivierzal)

The solution to log in again (device settings > maintenance, or from app settings) worked for many users.

Kind regards
