### ISSUE TITLE
Energy usage and COP data missing in release v25.0.0

### ISSUE THREAD

**Issue by logchem** [OlivierZal/com.melcloud#253]
Hi @OlivierZal,
 
The v25.0.0 MELCloud app is missing the data for energy and COP.
This concerns the totals of the previous day regarding the consumption of: Hot water, Heating, Cooling and associated COP values. 

Can you add these again?

**Comment by logchem** [comment]
Found it.
These were disabled after the last update.
Now I turned everything on and now I see the tags again 👍

**Comment by OlivierZal** [comment]
@logchem, I confirm that all the values are there if you check the settings you're interested in:

![IMG_3719](https://github.com/OlivierZal/com.melcloud/assets/88216225/fe6d178e-4898-4f94-93ec-b6bcd4991eec)

**Comment by OlivierZal** [comment]
@logchem, I'm glad you solved it!

Sorry for the inconvenience, such an issue was expected because I made a big reshape, but I promise there shouldn't be any (big) change in the very next releases.
