### ISSUE TITLE
Heating mode not correct in release 26.0.0

### ISSUE THREAD

**Issue by logchem** [OlivierZal/com.melcloud#257]
Hi @OlivierZal ,

I am not able to change the heating mode and it's not displaying the correct heating mode:
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/8374bd56-d5a1-48ea-bc32-4472a11f7009)

**Comment by OlivierZal** [comment]
Hi @logchem, I'll investigate, can you please provide a guest access to olivier.zalmanski@me.com from the official MELCloud app?

**Comment by logchem** [comment]
> [olivier.zalmanski@me.com](mailto:olivier.zalmanski@me.com) fr

Done

**Comment by OlivierZal** [comment]
@logchem, it has just been fixed!

**Comment by logchem** [comment]
Ok, I wil test when I receive the update :)
