### ISSUE TITLE
Power measurement not correct in release 26.0.3

### ISSUE THREAD

**Issue by logchem** [OlivierZal/com.melcloud#261]
Hi @OlivierZal ,

Yesterday in version 26.0.0 I saw the Power and Produced power:
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/27237e0d-ea4a-4200-b05d-ef8aae0ea12b)

Today, in release 26.0.3 the power is not correct:
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/6bd6f47d-c1e0-4dea-bcfb-5b5d60a41f3a)

Can you check this?
You still have access to my environment ;)

**Comment by OlivierZal** [comment]
Fixed in https://homey.app/sv-se/app/com.mecloud/MELCloud/test/

**Comment by OlivierZal** [comment]
Fixed in https://homey.app/a/com.mecloud/test
