### ISSUE TITLE
Missing triggers

### ISSUE THREAD

**Issue by janhjordie** [OlivierZal/com.melcloud#27]
Hey @OlivierZal 
I'm missing some of the triggers there were in the old version.
Triggers for defrost mode, booster heater 1 and 2 and immersion heater.

I also use the Operation Mode to show the heat pump state on the timeline, and the operation mode use to be ex. Off, DHW and Heating or something like that, but right now it's just values 0, 1, 2. (Not sure there are more) 
Could it be possible to get the text values back ? Or maybe an extra property with the text value

![image](https://user-images.githubusercontent.com/79910/197200467-9fb2bcaa-d2a0-4b8e-98cc-03ed6e81df6a.png)

**Comment by OlivierZal** [comment]
Will add them again, I thought I did but this all the new capabilities I probably misread within the too many flow cards.

**Comment by OlivierZal** [comment]
@janhjordie 

Concerning new labels, would it be ok for you?
```
"0" => "idle"
"1" => "dhw"
"2" => "heating"
"3" => "cooling"
"4" => "defrost"
"5" => "standby"
"6" => "legionella"
```

**Comment by OlivierZal** [comment]
I've just published a new test version.

**Comment by janhjordie** [comment]
Installed and testing !!

**Comment by OlivierZal** [comment]
I will make a small change at the immersion heater level (alarm_water => alarm_generic).

**Comment by janhjordie** [comment]
@OlivierZal 
"1" => "dhw" should be dwh, Domestic Water Heating

**Comment by OlivierZal** [comment]
I agree with you on a grammatical point of view, but if you search on Google (e.g.), you'll see results for DHW because it's a known acronym although there is not result for DWH, so I'd rather use DHW.

Actually it can be considered a shortcut for "Domestic Hot Water [Mode]", like "Heating [Mode]", "Defrost [Mode]" (and not "Defrosting").

**Comment by janhjordie** [comment]
Haha, ok, you win 😆
