### ISSUE TITLE
Defrost?

### ISSUE THREAD

**Issue by logchem** [OlivierZal/com.melcloud#295]
Hi @OlivierZal,

It is currently freezing in my place. But I never get the defrost message...
I can see in the graph that something is happening.
Is the defrost message perhaps not getting through properly?

![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/b18e2f2e-aa43-481f-8fbb-2af38599dd63)

Regards,
Peter

**Comment by OlivierZal** [comment]
Hi @logchem, what do you call the « defrost message »? You mean the « defrost alarm »? Can you help me reading your graph?

**Comment by logchem** [comment]
Hi @OlivierZal,

I can see this:
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/f41bde32-d566-4302-a02b-62d5109375ae)

But in the flow it's not working:
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/cece9f15-ff31-404a-9526-1345bbf8e9c2)

Can you check this?

Regards,
Peter

**Comment by OlivierZal** [comment]
So defrost alarm is well detected, but it seems that your screenshot deals with a completely different topic 😊

What does not work: do you get an error message, or is it that it is never triggered?

Can you screenshot the legionella last operation run from your device dashboard tab?

**Comment by logchem** [comment]
Sorry, wrong picture....
Switching to operation Legionella works OK.
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/87735f7c-d1a4-438c-b058-98f46b7b3782)
But I never receive the operation changed to Defrost.

**Comment by OlivierZal** [comment]
Yes 😊

I have a guess, I’ll keep you informed…

**Comment by OlivierZal** [comment]
@logchem,

It's not strange: the values from the tab you've screenshotted and the ones you use in your flow are not the same.

- in the tab: the values are booleans, included ones called "alarm" in MELCloud ("AlarmBoosterHeater1", "AlarmDefrostMode"...)
- in your flow: the values comes from the MELCloud "OperationMode", whose values are a number (0 = "Idle", ..., 4 = "Defrost", ...)

Some thoughts:
- it's normal that the "Legionella" OperationMode does not appear under this tab (it will never do so)
- if you receive a notification for "Legionella" OperationMode changes, it means that your flow work, and practically that means that in MELCloud the "Defrost" value (4) never happens
- if you see that "AlarmDefrost" turned on under the tab, that probably means that its meaning is different than the "Defrost" OperationMode.

**Comment by OlivierZal** [comment]
@logchem,

It's not strange: the values from the tab you've screenshotted and the ones you use in your flow are not the same.

in the tab: the values are booleans, included ones called "alarm" in MELCloud ("AlarmBoosterHeater1", "AlarmDefrostMode"...)
in your flow: the values comes from the MELCloud "OperationMode", whose values are a number (0 = "Idle", ..., 4 = "Defrost", ...)
Consequently:

it's normal that the "Legionella" OperationMode does not appear under this tab (it will never do so)
if you receive a notification for "Legionella" OperationMode changes, it means that your flow works, and practically that means that in MELCloud the "Defrost" value (4) never happens – then the question would be why...
if you see that "AlarmDefrost" turned on under the tab, that probably means that its meaning is different than the "Defrost" OperationMode.

**Comment by logchem** [comment]
Hi @OlivierZal,

Ok, so the descriptions are not correct?
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/726fac9a-b8ac-4fea-9b9a-241bb58b3c23)

Regards,
Peter

**Comment by OlivierZal** [comment]
There is no official MELCloud documentation, but there's a consensus (with the Home Assistant app for example) to say that these descriptions are correct.

Problem could also be on MELCloud side or on the comprehension we have of this value compared to the defrost alarm. It also can happen that some values are deprecated, that is, not used anymore but still exist. I will try to investigate.

**Comment by OlivierZal** [comment]
@logchem, after verification with an expert, the defrost operation mode does not exist anymore, you need to rely only on the "defrost mode alarm".

I'll remove the value in the next release.
