### ISSUE TITLE
Several actions not working anymore

### ISSUE THREAD

**Issue by Kaare69** [OlivierZal/com.melcloud#297]
Cards for operation mode,l and vane directions complain about ‘value type. Expected string. Got: number’. 

This is for air-to-air heat pump of course. 
running latest version with 29.0.0 from today.

**Comment by OlivierZal** [comment]
Yes, I can reproduce and investigate why some actions are broken...

**Comment by OlivierZal** [comment]
Hi @Kaare69, [identified](https://community.homey.app/t/app-pro-melcloud-melcloud-extension-take-control-of-your-heat-pumps/73094/149?u=olivierzal) and fixed in the next release, which can be downloaded as a test version: https://homey.app/a/com.mecloud/test/
