### ISSUE TITLE
DHW Temperature - Add to screen

### ISSUE THREAD

**Issue by kajo23** [OlivierZal/com.melcloud#299]
Please add DHW Temperature on this screen

![DHW - Show](https://github.com/OlivierZal/com.melcloud/assets/38912495/f8c9df0a-67e0-4286-af88-01078ba32b78)

**Comment by OlivierZal** [comment]
Hi @kajo23, with Homey design, when a temperature is measurable AND settable, they are displayed together under the temperature tab.
