### ISSUE TITLE
App disappear from installed Apps

### ISSUE THREAD

**Issue by Dome0068** [OlivierZal/com.melcloud#301]
Hello,
After Homey v10.2.1 installed, 1 time a day the MELClous APP disappears from installed Apps and all related devices doesn't work.
I need every time to reinstall it from App Store.
Please help and let me know

**Comment by OlivierZal** [comment]
Hi @Dome0068, I'm sorry for that...

I'm not experiencing this issue, but it's not related to the MELCloud app but to Homey core.

So unfortunately you need to contact the Homey support :-(

Kind regards

**Comment by Dome0068** [comment]
Hello Olivier, thank you
I have already opened a ticket to Homey Support for that

Kind regards

**Comment by OlivierZal** [comment]
Hope they will solve it!

**Comment by Dome0068** [comment]
Hi Olivier,
I am already in touch with Dennis (Homey Support) in order to provide him a
diagnostic report as soon as as the issue will reappear

Thanks and regards
Domenico

Il giorno ven 12 gen 2024 alle ore 01:25 Olivier Zalmanski <
***@***.***> ha scritto:
