### ISSUE TITLE
Defrost mode changed to defrost - Not working

### ISSUE THREAD

**Issue by kajo23** [OlivierZal/com.melcloud#302]
Defrost mode changed to defrost missed from last 1-2 updates? It is a bug or?

idle, heating, dhw is working

**Comment by OlivierZal** [comment]
Hi @kajo23, I was told by MELCloud experts that this value was deprecated by MELCloud and replaced by the "defrost mode alarm", and then never shows up anymore under "current operation mode", that’s why I removed it. 

Did you ever see it under "current operation mode"? If so I can add it again, but the "defrost mode alarm" seems to be the most reliable capability about defrost mode.

**Comment by kajo23** [comment]
I never see defrost mode alarm

I see only idle, heating, dhw
