### ISSUE TITLE
Strange heating issue

### ISSUE THREAD

**Issue by janhjordie** [OlivierZal/com.melcloud#31]
@OlivierZal 
I suddenly experiencing a strange thing.
When I try set the room heating temperature, it sets the temperature just fine. But few seconds after, it return to the original temperature.
Same issue on the speedometer control and from the card

**Comment by OlivierZal** [comment]
Hi @janhjordie, I will check, is that with production or test release?

**Comment by janhjordie** [comment]
Test release

Maybe it could be something with the polling interval ?

**Comment by OlivierZal** [comment]
No it's more related to the effective flag conversion.

Feel free to go back to production version until I fix it.

**Comment by OlivierZal** [comment]
Ok, it was an hard one, JS does not like big hexadecimals. Will be fix in next test release.

**Comment by OlivierZal** [comment]
@janhjordie, ok, it was an hard one, JS does not like big hexadecimals. Will be fix in next test release.

**Comment by OlivierZal** [comment]
Published:  https://homey.app/a/com.mecloud/test/

**Comment by janhjordie** [comment]
Damn, you are working late ! 

Installed now and will test during the day 

Thanks !

**Comment by OlivierZal** [comment]
@janhjordie, do you confirm your issue is solved?
