### ISSUE TITLE
An unknown error occurred after upgrading to ver 30.0.0

### ISSUE THREAD

**Issue by ChristerSjo** [OlivierZal/com.melcloud#311]
After upgrading to ver 30.0.0 for an hour ago i get this message.

![image](https://github.com/OlivierZal/com.melcloud/assets/41439454/e97c7dc9-7472-471c-a62a-5efcd1b0b9e3)

**Comment by ChristerSjo** [comment]
I have reboot SW and hard. I have tried to use the repair in the Home App with no success.

**Comment by AndreasR1** [comment]
Hi,
I have the same problem. Worked great until the latest update. Logging in again / repair /restart does not help

**Comment by OlivierZal** [comment]
Hi @ChristerSjo and @AndreasR1, can you please provide a guest access to olivier.zalmanski@me.com from the official MELCloud app so I can debug?

**Comment by ChristerSjo** [comment]
I think I have done that now. Did you get an invitation?

**Comment by logchem** [comment]
After update to release 30.0 I am not able to connect:
![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/725db816-0478-450e-86fa-2c0f29bf4597)

**Comment by kajo23** [comment]
I have the same issue as logchem
Device Unavailable

**Comment by OlivierZal** [comment]
Hi everyone, bug found, fix in progress, will be released in the very next minutes.

**Comment by OlivierZal** [comment]
Should be fixed with latest version 30.0.1 https://homey.app/a/com.mecloud/

Sorry for the inconvenience, the bug happened only for air-to-water devices, while I have a air-to-air one...

@kajo23, I got some findings concerning defrost operation mode, will investigate further.

**Comment by logchem** [comment]
It's working again :)
