### ISSUE TITLE
Melcloud error: "We have detected excessive traffic from your account, your access to the service has been limited for a few hours."

### ISSUE THREAD

**Issue by marium0505** [OlivierZal/com.melcloud#324]
Melcloud gives me  the following error when attempting to sign in to Melcloud:

> We have detected excessive traffic from your account, your access to the service has been limited for a few hours.
It's been there for over a day now. 

I can almost guarantee this isn't cause of something I do, or that my account details have been shared as I use a password generated password with a length of 18 chars with both symbols and, letters and numbers which I only keep in a password manager. 

I am, however using the Melcloud app on both a HP19 and a HP23 to control 2 Melcloud pumps.

So I'm pretty sure this is due to the way the app is set up. It is likely due to too many pollings from Melcloud's servers to get current consumption, fan speed etc.

**Comment by OlivierZal** [comment]
Hi @marium0505 

This issue stems from a change made by MELCloud 2 days ago, which appears to be aimed at blocking third-party integrations, as discussed here: https://github.com/home-assistant/core/issues/109728

It is still unclear what sync frequency will prevent MELCloud from banning Homey; testing is ongoing.
