### ISSUE TITLE
The operation mode is Fixed flow temperature reports false instead of true. 

### ISSUE THREAD

**Issue by kajo23** [OlivierZal/com.melcloud#328]
After last update The operation mode is Fixed flow temperature reports false instead of true.

**Comment by OlivierZal** [comment]
@kajo23, can you please provide examples, screenshots and some more explanations?
I don't understand a word of what you are saying...

**Comment by kajo23** [comment]
![image](https://github.com/OlivierZal/com.melcloud/assets/38912495/ef7d1773-6dd8-4678-98d4-88ac4b7956e2)

it is fault instead of true

**Comment by OlivierZal** [comment]
Ok, I understand better. 

Can you please screenshot the values you see for operation_mode_zone.zone1 / zone2 in this page: https://tools.developer.homey.app/tools/devices ?

**Comment by OlivierZal** [comment]
I found the bug but since I'm away from home I won't be able to test and deploy before next week.
I'll keep you updated when fixed.

**Comment by OlivierZal** [comment]
Should be fixed with the newest version
