### ISSUE TITLE
Fan speed settings not working in air to air heatpump

### ISSUE THREAD

**Issue by Therooster3** [OlivierZal/com.melcloud#350]
First i want to thank you for your work.

I use this to control the fanspeed and direction according to the measured power of the unit since fixed fanspeeds or auto speed does give big variations in temperature and comfort.

Since the ast update there is an issue with the fanspeed.
- the fanspeed is removed from the AND function. This check can cause too manny requests to the melcloud and they block  for several hours.
- in the THEN function the speed setting is changed to a slider. Unfortunately the slider only has 0 or 1

Can you fix this or is there a possibility to go back to the previous version?
I have the MUZ-LN35VG2
If I can help in testing, i have no programming skills, please let me know.
Kind regards

**Comment by OlivierZal** [comment]
Hi @Therooster3,

Thanks for having raised the issue, indeed I forgot one parameter. I’ll deploy the fix ASAP and keep you informed. 

Kind regard

**Comment by OlivierZal** [comment]
@Therooster3, fixed in this new version: https://homey.app/a/com.mecloud/test/

**Comment by Therooster3** [comment]
@OlivierZal 
Thanks for the fast fix. Sorry I could not test earlier. Was away and did not want to risk it for my wife.
The fan setting slider in the then section is working again.
It would be good to have this also in the AND section to check if te fan speed is already at the desired value to prevent continuous setting the fan speed at a setting it is already on.
Note, if you are sending too many commands melcloud blocks you for several hours. Happened to me before i put in this check in. At the moment i do this with a logic check.
![IMG_1254](https://github.com/OlivierZal/com.melcloud/assets/161309579/e35cf1a1-b507-4934-bf14-312d62875f79)

Kind regards

**Comment by OlivierZal** [comment]
Hi @Therooster3,

I didn't implement the AND card because there is no specific Homey component to handle range capabilities, so it can be handled by a standard "logic" card. 

I'm aware about the new MELCloud blocking, but I implemented a security to avoid it some release ago: when did it happen last? Does it still happen?

**Comment by OlivierZal** [comment]
To continue this important discussion, I invite to join https://slack.athom.com/, will be easier.

**Comment by Therooster3** [comment]
@OlivierZal 
I am on slack now, as well as in the homey comunity.
My name there is TheRooster, without the 3.
Will continue there
