### ISSUE TITLE
And card for Fan speed is gone in 32.3.1

### ISSUE THREAD

**Issue by Oddybear** [OlivierZal/com.melcloud#354]
Hi
I got a broken flow in Homey that the And Flow card for fan speed is gone for my air to air heat pump. 
I have changed the flow to use logic instead so it works again now, but if this is not intended from your side, I just wanted to inform you of this. 

I also had to change the card for setting speed after last versions, but it now works again.

**Comment by OlivierZal** [comment]
Hi @Oddybear, thank you very much for your message.

Unfortunately Homey does not ease changelog communications, but you reacted the right way: now I use new standard Homey components to handle fan speed, and when a device is created, it also creates the right number of speeds.

Consequence: the fan speed action card needed to be updated (with the sliders) and the condition card can be easily handled with the standard logic card :-)

Sorry for the inconvenience, ideally I would create a in-app notification, but it would require some extra temporary code...
Kind regards
