### ISSUE TITLE
Pull Request for MQTT Feedback.

### ISSUE THREAD

**Issue by Deejaybaze** [OlivierZal/com.melcloud#36]
Hi. All is working well now, with the active version. One thing i can see that is bugging me.
I have HOMEY connected via the Mosquitto app to my Cloud-Broker and Node-Red client.
If i change operating mode on zone 1 from Heat Room to Heat flow, the unit changes to flow, and sets the assigned temperature. But y MQTT status is stil "0" (should be 1). It has now been 12 hours since the last chnge, and the ecodan is stil in "1" in the MQTT feedback, and my MELcloud shows "0". Need more info?

Best Regards.
Thomas Neumann

**Comment by Deejaybaze** [comment]
![Skärmavbild 2022-10-27 kl  22 51 14](https://user-images.githubusercontent.com/113287468/198395594-760fadfc-acd1-486f-b8d9-461ff8a26afb.png)
There are also some other digits that does not add up.....

**Comment by Deejaybaze** [comment]
Just noticed. If i de-activate the device in the MQTT-Hub (app in Homey) And Re-Activate it. All numbers gets updated. As i have figured out. This is the only app with this problem.

**Comment by OlivierZal** [comment]
Hi Thomas, thanks for your feedback.

I'm not familiar with the way MQTT works with Homey but I've just seen that its code is public on GitHub so I'll investigate.

I'll keep you updated.

**Comment by OlivierZal** [comment]
@Deejaybaze, maybe a lead: could it be that subcapabilities (`xxx.yyy`) are well created but since the point is replaced in capability name, the corresponding values are not well updated? Have you examples of other apps with subcapabilities well updated? If so it would be a fix to do on MQTT.

**Comment by Deejaybaze** [comment]
Thank you for the quick response. Do you mean decimals in the unit? 50.00 and in MQTT it is only 50 ? I do not think so. Because many of the mqtt digits are directly from the app, and may vary depends on the variable. Operation status on the zone 1 mode is only 0,1,2

**Comment by OlivierZal** [comment]
No, I was meaning the handling of capabilities with a dot like `target_temperature.tank_water` or `operation_mode_zone.zone1`

**Comment by Deejaybaze** [comment]
![Skärmavbild 2022-10-27 kl  23 34 58](https://user-images.githubusercontent.com/113287468/198402816-43d9229b-f378-4999-82df-c1e1669940bc.png)
Is that on the back-end? In the script itself? This is a snipout from MQTT. over some other units. I can provide you with more if needed.

**Comment by OlivierZal** [comment]
I think I'll better understand if I install MQTT myself. 

Do you have the same issue with values like `target_temperature` or `operation_mode_state`?

**Comment by Deejaybaze** [comment]
Ill just saw this. In you app you have something called "Format" witch shows the temperature. And in other sensors this is not present, or a fixed number.
![Skärmavbild 2022-10-27 kl  23 39 10](https://user-images.githubusercontent.com/113287468/198403637-dd208a2b-b4b1-4ced-ad94-24ba7306af6b.png)

**Comment by Deejaybaze** [comment]
> I think I'll better understand if I install MQTT myself.
> 
> Do you have the same issue with values like `target_temperature` or `operation_mode_state`?

I would say most of the digits provided from the MELcloud App.

**Comment by Deejaybaze** [comment]
These are the units i use (for now, expanding when time comes). 
"Bör-Värde" is Target Temperature Zone 1
"Vattentanken" is temp in boiler
"Värmepanna Läge" is operation mode.

**Comment by Deejaybaze** [comment]
![Skärmavbild 2022-10-27 kl  23 42 38 1](https://user-images.githubusercontent.com/113287468/198404244-6a38908f-f312-4447-83a9-cde7526d1fbd.png)

**Comment by OlivierZal** [comment]
If you find values which are fine, share their names with me: it could help me the differences between working and non-working values.

**Comment by OlivierZal** [comment]
> ![Skärmavbild 2022-10-27 kl  23 34 58](https://user-images.githubusercontent.com/113287468/198402816-43d9229b-f378-4999-82df-c1e1669940bc.png)
> 
> Is that on the back-end? In the script itself? This is a snipout from MQTT. over some other units. I can provide you with more if needed.

What I see is that some values have their names changed compared to MELCloud and some others not. It could explain why some are not updated. If it's confirmed I will create an issue in the MQTT project.

**Comment by OlivierZal** [comment]
If my guess is right, the values without `.ˋ should be the one working, and the ones with `.ˋ should not: https://github.com/OlivierZal/com.melcloud/blob/master/drivers/melcloud_atw/driver.js

**Comment by OlivierZal** [comment]
Hi @Deejaybaze, I've made some research and found some similar issue raised for other devices / apps on MQTT's project:
- https://github.com/harriedegroot/nl.hdg.mqtt/issues/57 (last comment 21 days ago)
- https://github.com/harriedegroot/nl.hdg.mqtt/issues/74
- https://github.com/harriedegroot/nl.hdg.mqtt/issues/78
- https://github.com/harriedegroot/nl.hdg.mqtt/issues/80

**Comment by OlivierZal** [comment]
Hi @Deejaybaze,

I started the investigation.

I installed https://homey.app/fr-fr/app/nl.scanno.mqtt/MQTT-Client/ and I can see in the logs that your measures are well updated:

![image](https://user-images.githubusercontent.com/88216225/198819630-56ee6e39-09ac-42f0-9664-525af465504b.png)
![image](https://user-images.githubusercontent.com/88216225/198819637-db43d6bd-e4f4-4327-a404-95b9907a28de.png)

**Comment by OlivierZal** [comment]
I see there are 2 apps Mosquito MQTT client, do you use the same than mine?

**Comment by Deejaybaze** [comment]
![523E147D-AD55-4636-9E22-0ECBFCA6D805](https://user-images.githubusercontent.com/113287468/198820033-114fc10c-dcad-496b-a966-f0a26c96f7bc.jpeg) These are the apps I have.

**Comment by OlivierZal** [comment]
I use the same ones. And then you are seeing the values on RED Node, right?

**Comment by Deejaybaze** [comment]
Yes. It’s like the app works for 1-2 days. Then it does not provide statistics any longer until I restart the app (MELCloud).

**Comment by OlivierZal** [comment]
And once you restart the app, does it work for some time (I mean e.g. more than 2 hours), or only once and no longer?

**Comment by OlivierZal** [comment]
I have an idea, can you please send me a screenshot of your devices on MQTT hub settings? I wonder if you have a conflict between your "old" and "new" MELCloud devices (the one you recreated after I add consumption features).

**Comment by MTRKhn** [comment]
> Yes. It’s like the app works for 1-2 days. Then it does not provide statistics any longer until I restart the app (MELCloud).

Is your polling interval lower than 3 minutes. I noticed than if you go lower than 3, you hit some throttling and sync is blocked since you restart the MELCloud app…

**Comment by Deejaybaze** [comment]
It works for 1-2 days again.

**Comment by Deejaybaze** [comment]
> I have an idea, can you please send me a screenshot of your devices on MQTT hub settings? I wonder if you have a conflict between your "old" and "new" MELCloud devices (the one you recreated after I add consumption features).

I have deleted the old unit in both hub and in my broker.

**Comment by Deejaybaze** [comment]
> > Yes. It’s like the app works for 1-2 days. Then it does not provide statistics any longer until I restart the app (MELCloud).
> 
> Is your polling interval lower than 3 minutes. I noticed than if you go lower than 3, you hit some throttling and sync is blocked since you restart the MELCloud app…

Poling is 5 mins

**Comment by OlivierZal** [comment]
So I will wait 1-2 days to see if it also sticks on my side. 

1-2 days seems random: MELCloud app behavior remains the same in the time...

**Comment by OlivierZal** [comment]
@Deejaybaze, just to let you that I never give until I get a solution, or at least a root cause 🙂

**Comment by Deejaybaze** [comment]
I have my mqtt monitor active on my Mac to monitor all the changes in the variables. So I can see all the apps that might fail.

**Comment by OlivierZal** [comment]
Which RED node install did you choose? Docker? From node? Clone from GitHub?

**Comment by Deejaybaze** [comment]
I have my own cloud server in London. Running Ubuntu 20 LTS. Brooker and RN on same server.

**Comment by Deejaybaze** [comment]
Found it.

I have also the brooker app installed from my previous tests. Even tho i have all links pointed to my cloud server, the local brooker made calls to the client app, and that resulted in a loop for the MELcloud MQTT variables. I could see the "Moquitto Broker" app took huge amount of memory for some reason. I have now deleted the app, and see if my problems are gone.

**Comment by OlivierZal** [comment]
Hi @Deejaybaze, since you didn’t raise an problem since this weekend I close this issue. 

I’ve just seen that in your app review you wrote:

> I Can not Control my Ecodan after the 3.0.0 update. Do I need a update if the ecodan?

Did the new app versions solve your issue?

Kind regards

**Comment by Deejaybaze** [comment]
> Hi @Deejaybaze, since you didn’t raise any problem since this weekend I close this issue.
> 
> I’ve just seen that in your app review you wrote:
> 
> > I Can not Control my Ecodan after the 3.0.0 update. Do I need a update if the ecodan?
> 
> Did the new app versions solve your issue?
> 
> Kind regards

Hi O. 
mat the moment i have No problems with the App.

**Comment by OlivierZal** [comment]
Super! Don't hesitate to update your review so potential users could know everything works well :-)

**Comment by OlivierZal** [comment]
Super @Deejaybaze!

Don't hesitate to update your review on Homey, so potential users will know that the app works well :-)
