### ISSUE TITLE
Invalid capability, expected number, got string

### ISSUE THREAD

**Issue by DavidDjerf** [OlivierZal/com.melcloud#369]
After update to 33.0.1 my flows don't work anymore. Getting this error:

Invalid capability (homey:app.com.melcloud:fan_power) value type. Expected: number. Got String

**Comment by DavidDjerf** [comment]
Seems like if all fan speed cards are re-added (not replaced) it works again.

**Comment by OlivierZal** [comment]
Hi @DavidDjerf, maybe I forgot to tell about it or was not explicitly enough in the change log: I’ve added a new « silent mode » capability, which exists on some devices. It made me rethink the way it was originally handled in the app, and now respect the MELCloud type, which is a number and not a string. 

Sorry for the inconvenience.
