### ISSUE TITLE
On/off status problem

### ISSUE THREAD

**Issue by rwwh** [OlivierZal/com.melcloud#370]
We’re only using the system since about a week, and since yesterday morning the system no longer seems to be switching on correctly. We have an air-air heatpump (multi split), and when my flow decides to set the temperature, mode to heat and switch on the unit, the unit shows up as “on” in homey, but in my room it is still off. I can toggle it off and on manually and then it works, but somehow the flow does not switch it on.  I tried also with a delay of 2 seconds on the “switch on” card, no luck.

**Comment by rwwh** [comment]
![IMG_2099](https://github.com/OlivierZal/com.melcloud/assets/418043/9e84ae63-9676-4aee-8ddd-07a1e5219332)
![IMG_2100](https://github.com/OlivierZal/com.melcloud/assets/418043/c660d9f7-d8c6-40d3-b2fd-c5c1d4affc7c)

**Comment by OlivierZal** [comment]
Hi @rwwh, I’ll try on my side. 

On your side can you please remove the « when » conditions, run the flow manually (by clicking on the top play button) and tell me what happens?

**Comment by OlivierZal** [comment]
@rwwh, I’ve just made the test and it works on my side without « when » cards so I wonder if the issue couldn’t come from them.

By the way, the card « Set to the mode heat » both turns on and set to mode heat, so no need to set the 2 cards. 

![IMG_4099](https://github.com/OlivierZal/com.melcloud/assets/88216225/59f0b7e1-0d79-49b9-9dbd-b74cd606b8c5)

**Comment by OlivierZal** [comment]
But maybe I have a lead: I’ve raised a bug to Athom/Homey regarding thermostat mode capability change working randomly on the new iOS app v8.0+. Which is your app version?

Can you try to launch your manually from the web app (https://my.homey.app/) and tell me if it works?

**Comment by OlivierZal** [comment]
Hi @rwwh, remove the « turn on » should solve the issue since the « set to mode heat » card also turns on your device if it’s off. 

That’s this redundant action which makes the system think there is no change to apply. 

Can you please try and confirm me it works again?

**Comment by rwwh** [comment]
Thanks for the hint that it is not needed to switch on the system after setting it to heat. I played with it a little more, removing that card and adding 5 seconds before setting the heat mode after setting the temperature. 

Strange thing is that it had worked for almost a week without any problem.  

Now setting the desired temperature value did not switch on the unit, but in the “device status” the unit was on! When I turned it “off” using the device directly, and then ran the flow manually again, the unit turned on. Somehow apparently it is possible to have a device that is “off” report as “on” in Homey. I need to figure out a way to debug that now.

**Comment by OlivierZal** [comment]
Because of recent MELCloud restrictions, a device’s status in Homey cannot be refreshed more than every 5 minutes, otherwise the device will be stuck (even the access to the official MELCloud app will be blocked). 

I advice you not adding a delay between temperature and mode settings, because without delay the data will be sent to MELCloud in one single call. MELCloud API is not very robust, so it worth avoiding multiplying the calls.

**Comment by DavidDjerf** [comment]
I would like to add to this issue... if I use the melcloud-app flow card, the status is wrong. But if I use the logic card its correct.

![melcloud_onoff](https://github.com/OlivierZal/com.melcloud/assets/39162087/9e0824ce-256d-4c2c-b444-e5e9e9c5acc8)

**Comment by OlivierZal** [comment]
The first is automatically generated by Homey / Athom, but it works for me.

Can I see the whole workflow or even a short video?

Would be easier to discuss and debut on http://slack.athom.com

**Comment by OlivierZal** [comment]
@rwwh and @DavidDjerf, this test version should fix some of the issues you encountered: https://homey.app/a/com.mecloud/test/

**Comment by rwwh** [comment]
Hi Olivier, thank you very much and very sorry I have not been more responsive.
Since my issues have been resolved by applying your expert advice to my flows, it is not simply a question of dropping in the test version to see whether it would have resolved the issue. Do you have a suggestion of how I can best test the new version for you?

**Comment by OlivierZal** [comment]
Thanks for your answer @rwwh and no worries 😉 

No need to test, I had confirmation with my own ones. 

Thanks!

**Comment by DavidDjerf** [comment]
Sorry for no reply. Seems to be working just fine! :)
