### ISSUE TITLE
Air to air vent speed

### ISSUE THREAD

**Issue by iFac3** [OlivierZal/com.melcloud#378]
Hi there,

Huge thanks for your work on this app! 🙌

I experience weirdness with fan vent speed of my air conditioner. My automation should starts on 4th level, then set to 1 when the temperature rises. It always starts on 1 instead, while under device settings I see 6 as current fan speed and 500% at the dimming page. If I set percentage, it adopts as should.
![IMG_4431](https://github.com/OlivierZal/com.melcloud/assets/51527573/15aa56c2-71cc-4d26-b136-f70c446f13d9)
![IMG_4430](https://github.com/OlivierZal/com.melcloud/assets/51527573/123c2524-c421-4853-8072-6f5967fd6bbe)

**Comment by OlivierZal** [comment]
Hi @iFac3,

Thanks to your kind message!

Concerning the "crurent fan speed", that’s not the same value than "fan speed”. It scales from 0 (which is "inactive" and not "auto" like it is for "fan speed") to 6. To give you an example, when you’re in "auto fan speed", the "current fan speed" gives you the actual fan speed (which auto-adapt to the needs and changes). This value can also change when it’s not auto mode (🤷).

Concerning the fan percentage, that’s not a bug from my app but from Athom / Homey mobile app. I’ve raised it and am in touch with them. Can you confirm that all the values are correctly displayed in the web app https://my.homey.app/ ?

**Comment by iFac3** [comment]
Hi @OlivierZal,



> Concerning the "crurent fan speed", that’s not the same value than "fan speed”. It scales from 0 (which is "inactive" and not "auto" like it is for "fan speed") to 6. To give you an example, when you’re in "auto fan speed", the "current fan speed" gives you the actual fan speed (which auto-adapt to the needs and changes). This value can also change when it’s not auto mode (🤷).

I see.

> Concerning the fan percentage, that’s not a bug from my app but from Athom / Homey mobile app. I’ve raised it and am in touch with them. Can you confirm that all the values are correctly displayed in the web app https://my.homey.app/ ?

Yes, I checked, I can confirm, that in webapp it is more clear. 👌

Regarding the automation failure I've attached a screen shot (of the flow test). It starts up the machine, sets the required temperature, while the fan speed never adopts.

<img width="783" alt="Képernyőfotó 2024-04-04 - 7 44 56" src="https://github.com/OlivierZal/com.melcloud/assets/51527573/5fa23d15-fba4-40e1-8cfe-33a9690c1b29">

**Comment by OlivierZal** [comment]
I tested this flow and it worked:

![image](https://github.com/OlivierZal/com.melcloud/assets/88216225/e320e2fc-e8f7-45d4-9314-3df7cf0a8ff2)

Can you recreate the fan power card and try again?

**Comment by OlivierZal** [comment]
Hi @iFac3, I don't know if you saw the question below my big screenshot,

> Can you recreate the fan power card and try again?

**Comment by iFac3** [comment]
Hi Oliver,

I created the same flow:
￼



When I tested this flow with webapp, I’ve seen on my iPad, that fan level went to 4 from 1, but the AC unit did nothing. Then fan level display went back to 1 after a while.

Rgds,


Kálmán Gergely
***@***.***
+36 30 743 9610
