### ISSUE TITLE
Air-to-air fan speed to auto

### ISSUE THREAD

**Issue by barto74** [OlivierZal/com.melcloud#385]
I would like to be able to set the fan speed to auto with a Homey card in a flow. I believe this is not possible at the moment.
Its also not possible to set the fan speed to auto in the Homey interface - to me much less important, but still a nice-to-have.
Or am I missing both options?

**Comment by OlivierZal** [comment]
Hi @barto74, it's already possible :-)

Use the "fan speed" action card, and set the value to "0" (there's a tip in the card explaining that).

Tell me if you need support.

Kind regards

**Comment by barto74** [comment]
Thank you for the very quick answer! Highly appreciated!
