### ISSUE TITLE
migration issue (question)

### ISSUE THREAD

**Issue by Tonlaar** [OlivierZal/com.melcloud#388]
Migrated to from 2019 version to Homey Pro 2023. 
It took about 12 hours but now all apps are in memory. How/where do I enter the credentials of my MelCloud account?
Kind regards
Ton Laarhoven

**Comment by OlivierZal** [comment]
Hi @Tonlaar,

Normally you should be able to enter them either from **Homey** settings > MELCloud or from any **MELCloud device** settings > maintenance > repair. 

Does it work?

**Comment by Tonlaar** [comment]
Thanks for your response. Yes it works now :-)

**Comment by OlivierZal** [comment]
Glad to hear!
