### ISSUE TITLE
FW: app MELCloud - direct connection to the heat pump unit

### ISSUE THREAD

**Issue by radogr** [OlivierZal/com.melcloud#389]
Hello, Mitsubishi has had a server outage for several days and the MelCloud application is not working - it can't be set up via HomeyPro either. Is it possible to communicate and control the unit directly without using the Mitsubishi server?

**Comment by MTRKhn** [comment]
Nope, there is no on prem API... Be prepared, last time Mitsubishi had such issue, it lasted for about 12 days.

**Comment by radogr** [comment]
ou s**t  :(
thanks you for information

**Comment by OlivierZal** [comment]
Now it’s working again.

**Comment by radogr** [comment]
Yes, is back from 21:00 middle Europe tíme. Thank you

Dňa ut 23. 4. 2024, 6:50 Olivier Zalmanski ***@***.***>
napísal(a):

**Comment by radogr** [comment]
This is road to finish with HA, van tou upgrade for Homey?
Hardware update is easy :)

https://github.com/gekkekoe/esphome-ecodan-hp


Dňa ut 23. 4. 2024, 7:38 Radovan Grosch ***@***.***> napísal(a):

**Comment by radogr** [comment]
And mqtt connect or for ecodan... 
https://www.ebay.co.uk/itm/325967595655
