### ISSUE TITLE
Air to air outside temperture

### ISSUE THREAD

**Issue by ronennieshow** [OlivierZal/com.melcloud#396]
Hi 

First of all thanks for all the great work you have been done

But first the outside temperture workt just fine 
Since last night it has stopped. It does not show the temparture anymore. 

I have restart the app 
Restart the homey 

No result so far.

The ecodan is working just fine.

![image](https://github.com/OlivierZal/com.melcloud/assets/113858484/e310fbf4-e297-41b8-8cc6-26488b2c3914)

![image](https://github.com/OlivierZal/com.melcloud/assets/113858484/32d839ce-9e6e-430e-8e15-e8e7a3a036ef)

**Comment by OlivierZal** [comment]
Hi @ronennieshow, thanks for your feedback!

Can you please provide olivier.zalmanski@me.com with a guest access from the official MELCloud app (https://app.melcloud.com), so I can confirm that the problem is on MELCloud side?

Kind regards

**Comment by ronennieshow** [comment]
The inventation is send

**Comment by OlivierZal** [comment]
Bad news, the issue is 100% on MELCloud / Mitsubishi (not on Homey / app side).

<img width="470" alt="Capture d’écran 2024-05-15 à 11 20 41" src="https://github.com/OlivierZal/com.melcloud/assets/88216225/8ec09ee1-b0ee-41c8-8a6a-f39d7958afc3">

So there's nothing I can do at my level :-(
