### ISSUE TITLE
Frequency is always 0 on my Ecodan Heatpump

### ISSUE THREAD

**Issue by novicell-jhj** [OlivierZal/com.melcloud#4]
Hey @OlivierZal 
Thanks for helping/take over the code for Gerard ! ❤️ 

I just notised several changes in the UI.
There us to be more values on the property page. And notised the frequency is always 0, and know it's more than 0 right now, since the heatpump is running.

![image](https://user-images.githubusercontent.com/113981570/192869626-f1fb919a-df7b-4cc4-b6ed-fb4677e62356.png)

The property page also use to show the inside temp, but I can see that is now shown on the tile
![image](https://user-images.githubusercontent.com/113981570/192870581-b7413d08-f44e-469b-ac97-fe6ae9ac3bc0.png)

I have some logic using the frequency, so that would be very nice to get back on

Thanks
Jan

**Comment by OlivierZal** [comment]
Hi, I will have a look asap and give you a feedback tomorrow. 

Have you any other issues? Do you succeed in controlling the other HP params? Are you other flows still working?

**Comment by novicell-jhj** [comment]
There is something very wrong.
When I try set the heat water flow to ex. 35 degrees, it change the heat type from flow to room. And also set the heat water flow to 25.
If I try set the temperature to 10, it sets the temperature to 30 or 25, and also change the heat type from flow to room.

I hope you can figure out what it is. It has been running perfectly for a year, and now none of my HP flows works

**Comment by novicell-jhj** [comment]
If possible, we can make a teams session tomorrow, so I can show you what happens.

I have spent so many hours to optimize my house, and ex. charging the hot water tank with water when the electricity is cheapest and so on. And right now nothing works.

**Comment by janhjordie** [comment]
I just saw I used my work Github account, this is my normal Github account.

**Comment by janhjordie** [comment]
This is in MELCloud. It change from flow to room, and that's after I just try to set the hot water flow temperature

![image](https://user-images.githubusercontent.com/79910/192893130-fb4955ba-8ff8-4970-8ae9-34df823f1489.png)

![image](https://user-images.githubusercontent.com/79910/192893381-383d1bfd-e246-4382-9766-8bcaa4959377.png)

**Comment by OlivierZal** [comment]
Thanks for the screenshots. Could you also send me the 2 corresponding screenshots of Homey?Le 28 sept. 2022 à 23:38, Jan Hjørdie ***@***.***> a écrit :﻿
This is in MELCloud. It change from flow to room, and that's after I just try to set the hot water flow temperature

**Comment by janhjordie** [comment]
Sure thing. In Homey it's called Zone Operation Mode (ZOM). 
And for some reason, when I use any method to set something, it sets the ZOM to Heat Thermostat instead, where it should do nothing. 

![image](https://user-images.githubusercontent.com/79910/192938430-001455ae-8805-4d29-ad17-c3bf8505ebd7.png)
![image](https://user-images.githubusercontent.com/79910/192938441-6e120d34-7154-48ce-8405-bb2f651487a4.png)

**Comment by janhjordie** [comment]
I just tried the following.

1. Set the Zone Operation Mode in MELCloud to Flow
2. Activated the Set Water Tank Temp Card in Homey (and only that card)

And then I can see the MELCloud reported the Zone Operation Mode was changed to Room

![image](https://user-images.githubusercontent.com/79910/192961154-41a349f7-7746-4e02-b086-b2a767b70a23.png)

**Comment by janhjordie** [comment]
ok, also notised the Set Zone Mode does not work at all. Tried to set it to Flow

![image](https://user-images.githubusercontent.com/79910/192961857-009f251a-7f63-4d47-b2fd-8313537e0ec4.png)

**Comment by OlivierZal** [comment]
Maybe it could be related to https://github.com/XattSPT/com.melcloud/pull/36I’ll probably roll-back this commit. Le 29 sept. 2022 à 09:04, Olivier Zalmanski ***@***.***> a écrit :﻿Thank you it will help.Would you mind invite ***@***.*** as a guest from the official MELCloud app? Restricted (read-only) access should be enough to see MELCloud API behavior on your devices. Le 29 sept. 2022 à 08:58, Jan Hjørdie ***@***.***> a écrit :﻿
I just tried the following.

Set the Zone Operation Mode in MELCloud to Flow
Activated the Set Water Tank Temp Card in Homey (and only that card)

And then I can see the MELCloud reported the Zone Operation Mode was changed to Room

**Comment by janhjordie** [comment]
Hey @OlivierZal 
Please add me on LinkedIn, on https://www.linkedin.com/in/janhjordie/
Then you can send your email address to to me that way, so I can invite you to my MELCloud

Thanks !

**Comment by janhjordie** [comment]
You are now invited to my MELCloud with full access

**Comment by OlivierZal** [comment]
@janhjordie and @novicell-jhj, I think I get the issue, which is design-related to MELCloud API.
I try to send you a fixed test version when I'm back home tonight (in the late evening) so you can't test and won't have to wait for the stable release.

**Comment by MTRKhn** [comment]
Same problem here. Since yesterday, most of the values are not reported in Homey for my Heat Pump. Temperatures, frequency and some other values are not reported anymore since 3PM yesterday (Paris time), even after registering the device again in Homey.
![3C391BD0-D14A-4249-9063-E1D5DBE4A0D8](https://user-images.githubusercontent.com/72077818/193004288-847a865b-55b4-4b17-a463-40b8251e368a.jpeg)

![Uploading 8D16F01E-D877-40D0-A9F6-F912AC25CCC3.jpeg…]()

**Comment by janhjordie** [comment]
Thanks @MTRKhn for the image.
@OlivierZal, the image above shows exactly all the values there were visible in 2.0.12, and now are gone in your 3.0.2

**Comment by OlivierZal** [comment]
Hi everyone, I'm actually working on that and hope to provide you a test version by tomorrow. 

Thanks for your help.

**Comment by OlivierZal** [comment]
@novicell-jhj, I still see all these metrics on your device from my Homey

![image](https://user-images.githubusercontent.com/88216225/193017526-bb458cb9-1faf-47db-9d80-1107952a7ceb.png)

**Comment by janhjordie** [comment]
@OlivierZal That is SO strange
I have only 5 values, and tried from 3 Mac browsers (Chrome, Brave and Safari) and my iPhone

![image](https://user-images.githubusercontent.com/79910/193020531-9d5a7b3e-267f-4bea-88d6-1b948db6564c.png)

**Comment by janhjordie** [comment]
@OlivierZal maybe your screen/html view file is cached, since you don't have any values in most of the fields 
Try kill the app and open it again. Also try access it from https://my.homey.app/

**Comment by OlivierZal** [comment]
I don't think so since I added the device few minutes ago. 

The values are the issue I'm currently solving thanks to your guest access.

**Comment by janhjordie** [comment]
@OlivierZal Will it help your work if you get access to my Homey ? 

Thanks Oliver ❤️

**Comment by OlivierZal** [comment]
Yes of course, because at home I've only ACs. 

Once at home I will have your device logs.

**Comment by janhjordie** [comment]
I sent you a Homey invite link on LinkedIn

**Comment by OlivierZal** [comment]
Sorry @janhjordie, I read too fast, Homey won't help because I need to install and test locally, but you can invite me to your MELCloud as a guest (with restricted / read-only access) if you want.

**Comment by janhjordie** [comment]
@OlivierZal you are already in my MELCloud account https://app.melcloud.com/
I can see you have an active account in there

**Comment by janhjordie** [comment]
Any success @OlivierZal ?

**Comment by OlivierZal** [comment]
Testing right now

**Comment by OlivierZal** [comment]
I think I solved at least one of the bug.
Can I try to change from Flow to Room?

**Comment by OlivierZal** [comment]
@janhjordie, I think I solved at least one of the bug.
Can I try to change your HP from Flow to Room?

**Comment by janhjordie** [comment]
Sure thing. Please test

**Comment by MTRKhn** [comment]
> @novicell-jhj, I still see all these metrics on your device from my Homey
> 
> ![image](https://user-images.githubusercontent.com/88216225/193017526-bb458cb9-1faf-47db-9d80-1107952a7ceb.png)

You see this because you just registered the device in Homey. For existing ones, this is what is displayed (last update yesterday)

![Uploading D74E5DE2-C5EA-48F1-8E6A-5B8433C5A3A2.jpeg…]()

**Comment by janhjordie** [comment]
@MTRKhn I have used my Homey with my heat pump for more than a year, and looked at that page almost every day, and it was yesterday it changed look, after the version 3.0.2 was installed 
I have no idea how it's possible to have different views 
Could it be a locale setting?
I'm from Denmark

**Comment by MTRKhn** [comment]
Yeah same here, view was updated with the last update. 3PM yesterday, it’s the last value I have in Grafana. Message was for @OlivierZal sorry 😅

I assume HP values have been removed from 3.x version… it would be good to revert to the last 2.x version before there is a fix.

**Comment by OlivierZal** [comment]
Yes, and it confirms it works.
The bug comes from a tiny change in the Homey SDK 3.

**Comment by OlivierZal** [comment]
@janhjordie and @MTRKhn, can you please install https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/ and test?

**Comment by MTRKhn** [comment]
Just installed and values are now reported, yeaaaah. Only “problem”, even if it’s not a big one, is that my existing Homey device is missing a lot of values, I had to register the device again:

“Old” device (registered 1+ year ago):
![9F891567-014B-46E7-B8FF-02039F520F80](https://user-images.githubusercontent.com/72077818/193191980-a6bca8d9-873a-4c8a-8576-79beafa278c7.png)

Freshly registered device:
![E55167F6-0800-4A43-A83B-04FE75A15B6D](https://user-images.githubusercontent.com/72077818/193192044-ce95e7bc-4761-40ff-ad8a-d8daef20354e.png)

**Comment by OlivierZal** [comment]
Hi,

That’s an issue, and I don’t succeed in reproducing on my side… (I see all the values with a newly registered device). 

Would you mind add olivier.zalmanski@me.com as a guest with restricted (read-only) access to your MELCloud, so I can reproduce and test?

**Comment by MTRKhn** [comment]
Done. But I assume it’s more on the Homey side

**Comment by janhjordie** [comment]
@MTRKhn Do you also have a Ecodan air to water heat pump ?

**Comment by OlivierZal** [comment]
I added @janhjordie's one.

**Comment by OlivierZal** [comment]
@MTRKhn, it's strange because I see all your values too (see screenshot)

![image](https://user-images.githubusercontent.com/88216225/193196157-24ca0958-e9e0-4ee0-8d3c-4c80eda90203.png)

**Comment by MTRKhn** [comment]
> @MTRKhn Do you also have a Ecodan air to water heat pump ?

Yes. But just look at my edit below, my captures were switched. I have all values in the newly registered device but my « old » device is still missing some. No big deal I’ll switch my flows to the new device :)

**Comment by OlivierZal** [comment]
I think I understand what happens and can get this issue fixed (for you @janhjordie too).

**Comment by janhjordie** [comment]
@OlivierZal I tried to add my heat pump as new device, just like @MTRKhn 
And now the old HP is showing the short value list with 5 values, and the new one is showing 9 values, as it use to do.
I can also see it shows 2 difference icons on the same device type. Pretty strange. But hey, it correct again with the new install.

So far so good ! 

Since it's still using version 3.0.2, then the zone operation mode is not working.

![image](https://user-images.githubusercontent.com/79910/193211542-ba3d4a09-2ae5-4a7f-b4ee-0438f90b49d8.png)

And the frequency value are unknown. See image, it says Last value unknown. Can see it's same issue with the Hot Water Flow, Cold Water Flow, Booter Heater 1 and so on. All the places where there are a dash instead of a real value

![image](https://user-images.githubusercontent.com/79910/193213036-c8c53bc5-7ee8-4d6b-9ab2-539e7ef0af20.png)

**Comment by OlivierZal** [comment]
I don't understand, because when I see your device right now, I do see values. 

![image](https://user-images.githubusercontent.com/88216225/193217357-c0baa78b-46c5-44d3-b116-49c7866d9f28.png)
![Uploading 193217368...]

**Comment by OlivierZal** [comment]
@janhjordie, another thing strange in your comment: I deprecated "Heat Flow" in 3.0.2, so maybe the failure is that you need to change for a valid value from the drop-down. Can you please try and tell me?

**Comment by janhjordie** [comment]
@OlivierZal I know you made a pull request yesterday, with changes to the heat flow value, but is that updated on my Homey already ? You don't need to bump up the version ? (I don't know how the flow is from the Git repo to official Homey release)
![image](https://user-images.githubusercontent.com/79910/193220076-39e22639-e5d4-44d5-93a7-b3886e05ccf4.png)

The defrost mode showed on you screen says Non, is it french for No ?

![image](https://user-images.githubusercontent.com/79910/193219485-7def72ab-367c-4709-a0b2-5b3b5126e0e2.png)

**Comment by janhjordie** [comment]
Sorry, missed a screenshot

![image](https://user-images.githubusercontent.com/79910/193221368-e9e61641-fba4-4d69-93f4-191b15ae97a9.png)

**Comment by OlivierZal** [comment]
![IMG_1633](https://user-images.githubusercontent.com/88216225/193221714-1a984e68-d2f6-4f81-ab90-b8323ece7ab0.PNG)

I can't explain that... as well as I can't explain why I see values for your device on my end, and not you.

Now I can explain the other things:
- fact that old devices are not recognized can provide from the fact I defaulted zone 1, although it was explicitly set previously: I can fix it
- fact that "icons" disappears or "old values" remain is related to the fact SDK3 now requires lowercase for capability ids (there were some with uppercase): so maybe there are some flow cards to refresh in order to get the right ids.

**Comment by janhjordie** [comment]
@OlivierZal do you think I should try uninstall the MELCloud App ?
I would just be very sad if I had to, since it will break my big workflow 

![image](https://user-images.githubusercontent.com/79910/193223531-8f2e5a23-c08a-45e3-814f-cdfbb71a0012.png)

**Comment by OlivierZal** [comment]
No, it would break everything without helping.

I'm working to fix your issues :-)

**Comment by janhjordie** [comment]
@OlivierZal A thing that I never got to work with the old version, was the force hot water card.
So I had to make a javascript snippet to do it, and then call that from my flow

 await device.setCapabilityValue('forcedhotwater', true)
        .then(() => log('forcedHotWaterMode ON'))
        .catch(error => log(`Error:`, error));
        
        
I also think it's best to try fix, because all users with this app could have same issues.
Thanks for helping Olivier 😍

**Comment by OlivierZal** [comment]
I fixed a faulty code related to forced hot water, did you try again with new version?

**Comment by janhjordie** [comment]
How do I get the new version @OlivierZal ??
It still says 3.0.2 on my Homey 

It still gives this error when try change the value

![image](https://user-images.githubusercontent.com/79910/193227493-5fb68b5e-8511-4b08-9a16-71c387170e78.png)

**Comment by OlivierZal** [comment]
This is the newest version... (and mine).

Is it your "old" or your "new" device?
I will publish a new test version in about 1 hour.

**Comment by OlivierZal** [comment]
@janhjordie and @MTRKhn, can you please test this new version?
https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

**Comment by janhjordie** [comment]
Haha, great @OlivierZal 😆  I just installed your 3.0.4 test version, and it looks much much better now. But strange enough, it's only the newly added heatpump that shows the many values.

![image](https://user-images.githubusercontent.com/79910/193233388-1db6178f-f37a-43a0-b6d9-a901c604f26b.png)

**Comment by OlivierZal** [comment]
hmmm, maybe you need to do the switch now.

**Comment by OlivierZal** [comment]
hmmm, maybe you need to do the switch now due to SDK3 changes (it won't change anymore).

Do you confirm that now control is ok? (zone operation mode, forced hot water)

**Comment by janhjordie** [comment]
No, the zone operation mode does not work.

I have tried several times to set it to Flow, and set the heat water and cold water temp.

When Homey read the settings after the poll interval, it's set to Room and no values on hot and cold water temp
![image](https://user-images.githubusercontent.com/79910/193235062-e7c054d6-0271-4a02-89f9-8b8e62577a73.png)

**Comment by janhjordie** [comment]
YES !! Now the frequency works again 😃 

![image](https://user-images.githubusercontent.com/79910/193235909-95e8c85f-fcec-4136-8090-bee0dfa90938.png)

**Comment by OlivierZal** [comment]
@janhjordie, I confirm the zone operation mode modification issue.

**Comment by OlivierZal** [comment]
@janhjordie, have you flows changing the settings?

**Comment by janhjordie** [comment]
@OlivierZal, no, my flows will first run at 2pm today. I just tried it manually. You are also welcome to try do it from your location.

**Comment by OlivierZal** [comment]
@janhjordie and @MTRKhn, can you please test 3.0.5? (from https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/)

**Comment by MTRKhn** [comment]
Anything specific you want to test ?

some information are still missing on the « old » device. New one looks ok.

**Comment by OlivierZal** [comment]
For the reasons I mentioned above, due to SDK3 requirements, it seems the devices needs to reassociated (once for good).

Tests would consist to confirm there is no control/data issue.

**Comment by janhjordie** [comment]
@OlivierZal Still same issue with 3.0.5. It's not changing the Zone Operation Mode on the heatpump

![image](https://user-images.githubusercontent.com/79910/193251928-6f65603e-fb6f-45e3-ab82-3d33faf0082d.png)

![image](https://user-images.githubusercontent.com/79910/193252045-c569b221-ce70-4750-afe8-5e01a107dbc2.png)

If I change the Zone mode on the heatpump with the native MELCloud app, the Homey app read the settings correctly (screenshot 1), and just hit save, it sets the zone mode to Room again, and also set the Zone 1 Flow Temperature to 25, and not 36 as specified

**Comment by OlivierZal** [comment]
Hi @janhjordie and @MTRKhn, I think that now the issue is fixed. Will release a new test version in a couple of minutes.

Just one question: I see that MELCloud API (and Homey MELCloud API) propose to change the "Cool Water Temperature", but I don't see how to perform this action from the official MELCloud app – not how to choose "Cool Room/Flow" (versus "Heat Room/Flow").

Is something missing from the official app?
How can you switch from "Heat" to "Cool" from the official app?

**Comment by janhjordie** [comment]
@OlivierZal I don't have any options for cool water in the native MELCloud app. 
I guess it's something from the air to air heat pumps

**Comment by OlivierZal** [comment]
It's something specific to air to water HP, though.
I see how to configure "cool water temperature" (which is also specific to air to water HP) using the API, but I really wonder how we can set the "cool water temperature" from the app.

**Comment by MTRKhn** [comment]
It's for air to water HP that can both heat and cool down. Mine is only heating so option is not available.

**Comment by janhjordie** [comment]
@OlivierZal I have no idea how to do that. I have never seen that option in the native app, only in the Homey MELCloud app 😆 
It might be an option on some of the heat pumps models

![image](https://user-images.githubusercontent.com/79910/193276004-ef4b7a4a-7dfe-4cf9-bf3e-d819cfe2afa8.png)

**Comment by OlivierZal** [comment]
Got it

**Comment by OlivierZal** [comment]
@janhjordie and @MTRKhn, this version should work: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

Note that due to migration to SDK3, you may need to add your devices again and restart Homey (once for good).

Please tell me if you find any issue, in particular with flows.

**Comment by janhjordie** [comment]
@OlivierZal I can confirm the set Zone Operation Mode now works 😍

**Comment by OlivierZal** [comment]
@janhjordie and @MTRKhn, don't hesitate to open a new incident for any bug you would find. 

Regards

**Comment by OlivierZal** [comment]
Thank you it will help.Would you mind invite ***@***.*** as a guest from the official MELCloud app? Restricted (read-only) access should be enough to see MELCloud API behavior on your devices. Le 29 sept. 2022 à 08:58, Jan Hjørdie ***@***.***> a écrit :﻿
I just tried the following.

Set the Zone Operation Mode in MELCloud to Flow
Activated the Set Water Tank Temp Card in Homey (and only that card)

And then I can see the MELCloud reported the Zone Operation Mode was changed to Room
