### ISSUE TITLE
Insights data freezing

### ISSUE THREAD

**Issue by logchem** [OlivierZal/com.melcloud#403]
Hi @OlivierZal ,

The data is no longer correct since 2:00 PM yesterday. It is a straight horizontal line and shoots up and then stays horizontal again. I saw this because today my legionella program started today at 1:00 PM. At 1:00 PM the temperature was 47 degrees, and at 3:30 PM the temperature was 61.5 degrees.
Can you see what's going on?

![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/a3c690b6-2bce-4093-b666-4b69fc93b59f)

![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/d7eb4401-f152-4e80-aa6c-8513c49425d2)

![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/b61e5fdc-785f-4068-b71c-7f5c4b93ab92)

![image](https://github.com/OlivierZal/com.melcloud/assets/2377645/d4851120-d4b0-4af8-887f-9c78050f81cf)

**Comment by OlivierZal** [comment]
Hi @logchem,

Unfortunately that's not a Homey app issue, since there was no change yesterday: that's the data straight forward from MELCloud.

So either it is a MELCloud (= Mitsubishi data) issue or a device issue.

**Comment by logchem** [comment]
A restart of the Melcloud app fixed the problem. Data is comming in again 🙂

**Comment by OlivierZal** [comment]
I'm glad it works again!
