### ISSUE TITLE
Can't login through Homey

### ISSUE THREAD

**Issue by noehr2** [OlivierZal/com.melcloud#404]
<img width="440" alt="Skærmbillede 2024-05-23 kl  19 57 37" src="https://github.com/OlivierZal/com.melcloud/assets/128841404/470735ae-f15b-40ff-be25-0716cb284064">

**Comment by taskeladd** [comment]
Same problem for me.

**Comment by Fiskviken** [comment]
Same here

**Comment by Kevswe** [comment]
Same! It stoped responding and restating the app doesn’t work. I tried to log in but there’s an “unknown fault” message when trying. It was working fine until last night

**Comment by OlivierZal** [comment]
Hi,

It’s a MELCloud certificate issue (I didn't push any app update earlier today).

I’ve just published a new app version with a workaround.

Kind regards
