### ISSUE TITLE
Random update since 5.6.2

### ISSUE THREAD

**Issue by MTRKhn** [OlivierZal/com.melcloud#42]
Since 5.6.2 upgrade this morning, data are randomly acquired. Schedule is every 3 minutes but some data were not updated for like 30 minutes. Usually when a throttling happen, usually a restart of the app solves it but can’t make it work again :(

Generated a report: a6ac6421-4ea9-442c-9480-d9ad9c7d7460

**Comment by OlivierZal** [comment]
Hi @MTRKhn,

Unfortunately the report you generated doesn’t show anything concrete. 

Have a concrete example which would illustrate the issue?

**Comment by MTRKhn** [comment]
HP started an hour ago, flow temp and return temp were changing every morning according to the MelCloud app but no changes were reported in Homey. Frequency was not updated either. I just revert to 5.5.0 and everything works.

**Comment by OlivierZal** [comment]
And did you also have periods where everything update well?

**Comment by MTRKhn** [comment]
Flow and return temps were only updated 3 times today (2PM, 5PM and 8PM). But i see at least a change every hour in MelCloud

**Comment by OlivierZal** [comment]
Ok, I’ll investigate my own logs this night.

**Comment by OlivierZal** [comment]
Thanks to you I found an invisible bug…
Fortunately it’s very simple to fix, will do so tonight.

**Comment by OlivierZal** [comment]
@MTRKhn, fixed in the last test version.

**Comment by OlivierZal** [comment]
Hi @MTRKhn, do you confirm this morning that the last version solved your issue?

**Comment by MTRKhn** [comment]
All good ! Thanks !
