### ISSUE TITLE
insight data not updating after some time

### ISSUE THREAD

**Issue by bgelens** [OlivierZal/com.melcloud#431]
First off, thanks for this app! It really is helping me tuning my ecodan heathpump energy usage!

Unfortunately I've hit an issue though. Like with #403 the insight data freezes up. It can be either 0 or the last actual reported value and won't update until I restart the app. I even have a flow running that restart the app every night.

When I restart the app, insights is correct again. Today I had to restart 2 times already.

If there is something I can do to help analyze the problem, please let me know what to provide

The metric I'm monitoring is Power Usage

Homey early 2023 with version 11.1.0
Melcloud app version 36.2.0

**Comment by OlivierZal** [comment]
Hi @bgelens, thank you for your feedback!

Yesterday's 36.2.1 https://homey.app/fr-fr/app/com.mecloud/MELCloud/ should have solved the issue.

Kind regards
