### ISSUE TITLE
Melcloud app for Homey version 37.0.1  - crash on startup

### ISSUE THREAD

**Issue by vervuiler** [OlivierZal/com.melcloud#473]
Melcloud app for Homey version 37.0.1  - crash on startup.

30-07-24 / 22u | auto update to 37.0.0
31-07-24 / 01u | auto update to 37.0.1 - crashes during startup, app halted.

-
https://homey.app/en-nl/app/com.mecloud/MELCloud/

**Comment by heszegi** [comment]
Same issue here after auto update to 37.0.1

**Comment by OlivierZal** [comment]
Will have a look asap

**Comment by Oddybear** [comment]
Mine has also crashed after updated to 37.0.1

**Comment by logchem** [comment]
![Screenshot_20240731_070456_Homey](https://github.com/user-attachments/assets/1808c8c1-7713-4d66-9fad-fc3dd268bdfb)

**Comment by logchem** [comment]
![Screenshot_20240731_070711_Homey](https://github.com/user-attachments/assets/a55c2e2c-e1f3-454c-a849-4ffe9fddeef0)

**Comment by OlivierZal** [comment]
Seems to be fixed with latest version (37.0.3), not related to latest Homey module deployment, I rolled back to the previous one.

**Comment by vervuiler** [comment]
Thank you Olivier! Topmost support response!

**Comment by logchem** [comment]
Thanks! It works again :)
