### ISSUE TITLE
Melcloud crashed

### ISSUE THREAD

**Issue by davidgithub85** [OlivierZal/com.melcloud#477]
Melcloud crashed

Exit Code: 1,Exit signal: null

![image](https://github.com/user-attachments/assets/e1a43633-51c2-488e-a486-2f1e858bf685)

**Comment by OlivierZal** [comment]
Fixed with 37.0.3, it's related to a bug on Homey side happening only in production and which I workarounded.

**Comment by davidgithub85** [comment]
do i need to uninstall the app and reinstall for it to work?

**Comment by davidgithub85** [comment]
Fixed it works now thank you!

**Comment by OlivierZal** [comment]
If you activated the automatic updates, it should auto-update but I have no control on the timeline, so update manually is more secure. I'm debugging right now with Athom/Homey.
