### ISSUE TITLE
Melcloud app Homey werkt niet meer

### ISSUE THREAD

**Issue by ErikBoekestijn** [OlivierZal/com.melcloud#482]
Tot voor kort had ik mijn aircondioning (split unit van mitsubitsi) gekoppeld aan homey via de Melcloud app).
Dit werkte super.
Nu is de homey Melcloud app ineens verdwenen uit mijn Homey.
Als ik de app opnieuw installeer dan lukt het verbinden niet.  (blijft een zandloper staan)

Speelt dit bij anderen ook?
Zo niet wat kan ik proberen

**Comment by OlivierZal** [comment]
Hi,

I don't speak Dutch...

Can you please make sure you use the latest app version? https://homey.app/nl-nl/app/com.mecloud/MELCloud/

Otherwise please send me a diagnostics report from the Homey app.

Thanks

**Comment by ErikBoekestijn** [comment]
Thanks for your message, i finaly in succeed in connecting melcloud to homey, after resetting and deleting and install again



Verstuurd vanaf mijn iPhone



​Met vriendelijke groet,
Erik Boekestijn

​
​
Kijckerweg 105a  2678 AC De Lier
T: +31 (0)174 51 35 46
M:+316 20 01 19 43
​
www.boekestijn.net
​
Op 2 aug 2024 om 14:05 heeft Olivier Zalmanski ***@***.***> het volgende geschreven:

﻿
LET OP: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links of open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.


Hi,

I don't speak Dutch...

Can you please make sure you use the latest app version? https://homey.app/nl-nl/app/com.mecloud/MELCloud/

Otherwise please send me a diagnostics report from the Homey app.

Thanks
