### ISSUE TITLE
Melcloud

### ISSUE THREAD

**Issue by denpog2A** [OlivierZal/com.melcloud#493]
Bonjour 
L’extension pour MELCloud s’installe bien dans homey pro
Mais l’appli MELCloud a disparu et ne s’installe plus
Que faire ?
Merci beaucoup

**Comment by OlivierZal** [comment]
Bonjour,

Tout d'abord pouvez-vous vérifier que le firmware de votre Homey est bien le dernier (12.0.0) dans Plus > Paramètres > Mises à jour ?

Une fois mis à jour, installez https://homey.app/fr-fr/app/com.mecloud/MELCloud

Est-ce que cela résout votre problème ?

**Comment by denpog2A** [comment]
Merci de votre réponse
La version est correcte
L’appli ne s’installe toujours pas
J’espère qu’il y aura une solution

Merci encore

Denis POGGIONOVO
0616778078
***@***.***


Le mar. 6 août 2024 à 15:07, Olivier Zalmanski ***@***.***> a
écrit :

**Comment by OlivierZal** [comment]
Pouvez-vous m'envoyer les copies d'écran suivantes :
- version de Homey (rubrique mise à jour)
- applications (dans l'onglet "plus")
- vos devices

Et m'envoyer un rapport de diagnostic (dans les paramètres de l'application MELCloud). 

Si l'application n'arrive même pas à s'afficher dans l'app Homey, il faudra alors voir avec le support d'Homey, car cela veut dire que ce n'est pas relatif à l'application MELCloud.

**Comment by denpog2A** [comment]
Merci pour votre aide
Voici les vidages d’écran

Pour les sévices comment puis-je obtenir la liste ?


Denis POGGIONOVO
0616778078
***@***.***


Le mar. 6 août 2024 à 18:02, Olivier Zalmanski ***@***.***> a
écrit :

**Comment by OlivierZal** [comment]
Malheureusement je ne peux pas voir les copies d’écran lorsque vous répondez par mail : il faut que vous alliez repndnre sur http://github.com

Pour obtenir la liste des applications, il faut aller dans « Plus » > Applis

il est également possible de l’obtenir ici : https://tools.developer.homey.app/

![IMG_4904](https://github.com/user-attachments/assets/1fb1ee05-ae38-4b06-a91f-17386998a1a7)

**Comment by OlivierZal** [comment]
En l'absence d'élément nouveau pour investiguer, je ferme ma tâche. 

Vous pouvez toujours envoyer les éléments demain, et je regarderai.
