### ISSUE TITLE
Homey device slowly updated from MELCloud

### ISSUE THREAD

**Issue by jf84398942813** [OlivierZal/com.melcloud#500]
Hi team,
The Homey device is slowly updated (<5 minutes) before the status is updated.
Under the MELCloud app, the status is updated normally (<5s).
Could you update the device status more frequently ?

In addition, the "power" is not updating.

Thanks.

**Comment by OlivierZal** [comment]
Hi @jf84398942813,

It's not possible to update more often than 5 minutes anymore, because of a restriction from the official MELCloud (set ~6 months ago), which would block your account – and then any device update – between 30 minutes and 2 hours.

Concerning the "power" not updating issue: do you have any elements? (data, screenshots, step-by-step reproduction...).
Because I never experienced this issue myself, and received no such a feedback from other users.

Regards

**Comment by jf84398942813** [comment]
ok for the first point, I note the delay.
regarding the "power not updating issue", I can show you what I see with homey using Insight :
![image](https://github.com/user-attachments/assets/241ad5e2-9c85-40cf-8b66-27b2c39da49a)

And with the device directly,  I can show you the same device with 2 informations :
![image](https://github.com/user-attachments/assets/68af398a-79e3-4813-8ab2-f9aa21d90b36)
![image](https://github.com/user-attachments/assets/fe2c7b36-534c-479b-9695-9aaf692b9eac)
![image](https://github.com/user-attachments/assets/0990f82f-aa32-499a-a21d-951fb1457dc3)

First Power updated 2 hours ago, the second temp updated 3 minutes ago and the last representing the device.

I have 2 MELCloud device and thios occurs only with the 2nd device. For the first device, all is OK (shown with the Insight).

Tell me if you need more details.
Thanks

**Comment by OlivierZal** [comment]
Ah je comprends mieux : dans l'écosystème MELCloud "Power" signifie "on/off", tandis que c'est "Energy" qui signifie "Puissance/Énergie".

Alors il faut savoir que l'API "Energy" MELCloud n'est pas du tout fiable : elle est déduite à partir d'une valeur imprécise (kWh) actualisée seulement toutes les 2 heures – ce qui permet de donner une idée de la puissance moyenne (W) au cours des 2 heures précédentes, donc c'est loin d'être de la data "live"...

Par ailleurs, le temps sous les "capacités" ("il y X minutes/heures") ne représente pas le temps de la dernière actualisation, mais le temps depuis le dernier changement de valeur, ce qui peut laisser croire que l'appareil ne s'actualise pas, alors qu'en fait oui.

Un dernier point : ce que vous montrez semble confirmer le bon fonctionnement de MELCloud _dans Homey_. En effet, l'API "Energy" est distincte des autres APIs, et vos copies d'écran montrent qu'Homey reçoit régulièrement de la data à 2 heures d'intervalle. Le reste – comme les éventuelles incohérences de data – est malheureusement le fait de l'API MELCloud officielle. D'ailleurs, si vous allez dans l'app officielle, vous trouverez normalement la même data que dans Homey. Si ce n'est pas le cas, n'hésitez pas à m'envoyer des copies d'écran, que je pourrai analyser.

Cordialement

**Comment by jf84398942813** [comment]
je vois, merci pour les explications.

Mais si "Power" signifie "on/off", je devrais donc avoir un pic dans Insight à chaque allumage, non ?
L'idée de tout ca c'est vérifier si la clim est allumée, donc si elle consomme, alors qu'on n'est pas là (oublie, etc ..)

Mais un truc que je ne comprends pas, c'est pourquoi j'ai une telle différence entre mes 2 splits.
Le premier (en bleu) me donne bien des informations "cohérentes", alors que le deuxieme (en vert) n'est pas du tout représentatif.

C'est l'utilisation de la puissance qui m'intéresse, mais elle n'apparait pas dans l'application MELCloud. Je n'ai que les rapports d'utilisation d'energie

**Comment by OlivierZal** [comment]
La gestion globale des insights dépend d'Homey (Athom), pas de chaque app.

Concernant la puissance, la limitation vient de MELCloud : elle ne la remonte pas du tout pour les appareils air-air, et ne peut donc la déduire que très approximativement, et encore quand les valeurs de l'API "énergie" sont fiables.

Techniquement je ne fais que remonter les valeurs de l'API, qui sont celles remontées aussi dans l'app officiel. Si vous voyez des différences entre les infos dans Homey et celles dans l'app, c'est là que je peux investiguer un éventuel problème de communication.

**Comment by jf84398942813** [comment]
je comprends là où vous pouvez intervenir, c'est clair.
mais du coup, j'ai un cas concret :
- j'allume la clim depuis la télécommande
- > L'application MELCloud voit bien que la clim est allumée
- homey se met à jour quelques minutes plus tard et j'ai bien la tuile de la clim dans Homey qui devient active
- > a ce moment là, je n'ai pas le Insight "on/off". Cette information d'historique est importante pour savoir l'état d'allumage des clims dans le temps.

Pour la puisssance, je peux faire l'extrapolation en utilisant la puissance "théorique" consommée par le split, ca ne me gène pas.

Ce qui serait donc utile pour moi serait d'ajouter un Insight associé au "on/off".

Qu'en pensez-vous ?

**Comment by OlivierZal** [comment]
> Ce qui serait donc utile pour moi serait d'ajouter un Insight associé au "on/off".
> 
> Qu'en pensez-vous ?

Personnellement je n'ai rien contre, mais c'est une limitation de Homey: https://github.com/athombv/homey-apps-sdk-issues/issues/350#issuecomment-2213783789 (pas d'insights pour les capacités "booléennes"...).

**Comment by jf84398942813** [comment]
arf zut, dommage.
donc si je veux ca faut que je me crée un device avec mes propres insights, et au lieu d'utiliser les bool, j'utilise un int avec 0 ou 1.
c'est une manière détournée.

Et dernier point, pour les consommations d'énergies (dans mon Insight avec les 2 graphs), pourquoi j'ai une telle différence entre les 2 splits ? Le bleu semble cohérent et reflète la réalité, mais le vert pas du tout

**Comment by OlivierZal** [comment]
Un conseil : pour éviter une désynchro entre votre appareil, lancez les commandes depuis Homey plutôt que depuis l'app MELCloud ou la télécommande.

**Comment by jf84398942813** [comment]
> Un conseil : pour éviter une désynchro entre votre appareil, lancez les commandes depuis Homey plutôt que depuis l'app MELCloud ou la télécommande.

oui en effet, mais dans la vraie vie les 2 cas sont possibles, l'utilisation de la télécommande et depuis Homey. Mais c'est un détail, si ce n'est qu'un delta de temps, c'est acceptable

**Comment by jf84398942813** [comment]
> > arf zut, dommage.
> > donc si je veux ca faut que je me crée un device avec mes propres insights, et au lieu d'utiliser les bool, j'utilise un int avec 0 ou 1.
> > c'est une manière détournée.
> > Et dernier point, pour les consommations d'énergies (dans mon Insight avec les 2 graphs), pourquoi j'ai une telle différence entre les 2 splits ? Le bleu semble cohérent et reflète la réalité, mais le vert pas du tout
> 
> Il faut comparer avec ce qu'il y a dans l'app MELCloud, pour voir si ça vient de l'appareil, de MELCloud ou d'Homey.

je vous confirme que les valeurs homey vs MELCloud sont OK concernant le "Energie".
Les informations liées à "Puissance" ne sont pas disponibles dans l'application MELCloud, donc pas de comparaison possible avec les valeurs dans Homey. Cette information de consommation "instantanée" vous arrivez à la récupérer ? Dans l'application je ne la trouve pas.

**Comment by OlivierZal** [comment]
> > Un conseil : pour éviter une désynchro entre votre appareil, lancez les commandes depuis Homey plutôt que depuis l'app MELCloud ou la télécommande.
> 
> oui en effet, mais dans la vraie vie les 2 cas sont possibles, l'utilisation de la télécommande et depuis Homey. Mais c'est un détail, si ce n'est qu'un delta de temps, c'est acceptable

Oui bien sûr, c'est pour ça que je fais quand même une synchronisation toutes les 5 minutes.

**Comment by OlivierZal** [comment]
> > > arf zut, dommage.
> > > donc si je veux ca faut que je me crée un device avec mes propres insights, et au lieu d'utiliser les bool, j'utilise un int avec 0 ou 1.
> > > c'est une manière détournée.
> > > Et dernier point, pour les consommations d'énergies (dans mon Insight avec les 2 graphs), pourquoi j'ai une telle différence entre les 2 splits ? Le bleu semble cohérent et reflète la réalité, mais le vert pas du tout
> > 
> > 
> > Il faut comparer avec ce qu'il y a dans l'app MELCloud, pour voir si ça vient de l'appareil, de MELCloud ou d'Homey.
> 
> je vous confirme que les valeurs homey vs MELCloud sont OK concernant le "Energie". Les informations liées à "Puissance" ne sont pas disponibles dans l'application MELCloud, donc pas de comparaison possible avec les valeurs dans Homey. Cette information de consommation "instantanée" vous arrivez à la récupérer ? Dans l'application je ne la trouve pas.

Malheureusement elle n'existe pas (seulement pour les appareils air-eau, et encore de manière très imprécise). Je calcule bêtement :

```
Différence d'énergie entre 2 mesures (en kWh) / durée sur laquelle est mesurée cette énergie (2h) = puissance moyenne sur cette durée (kW = W x 1000)
```

**Comment by jf84398942813** [comment]
> > > > arf zut, dommage.
> > > > donc si je veux ca faut que je me crée un device avec mes propres insights, et au lieu d'utiliser les bool, j'utilise un int avec 0 ou 1.
> > > > c'est une manière détournée.
> > > > Et dernier point, pour les consommations d'énergies (dans mon Insight avec les 2 graphs), pourquoi j'ai une telle différence entre les 2 splits ? Le bleu semble cohérent et reflète la réalité, mais le vert pas du tout
> > > 
> > > 
> > > Il faut comparer avec ce qu'il y a dans l'app MELCloud, pour voir si ça vient de l'appareil, de MELCloud ou d'Homey.
> > 
> > 
> > je vous confirme que les valeurs homey vs MELCloud sont OK concernant le "Energie". Les informations liées à "Puissance" ne sont pas disponibles dans l'application MELCloud, donc pas de comparaison possible avec les valeurs dans Homey. Cette information de consommation "instantanée" vous arrivez à la récupérer ? Dans l'application je ne la trouve pas.
> 
> Malheureusement elle n'existe pas (seulement pour les appareils air-eau, et encore de manière très imprécise). Je calcule bêtement :
> 
> ```
> Différence d'énergie entre 2 mesures (en kWh) / durée sur laquelle est mesurée cette énergie (2h) = puissance moyenne sur cette durée (kW = W x 1000)
> ```

ok je comprends. je vous remercie grandement pour vos explications et retours d'informations.
je verrais avec le temps comment m'adapter à tout celà.

Je vous souhaite une bonne continuation.
Cordialement.

**Comment by OlivierZal** [comment]
@jf84398942813,

Should definitively solve any sync issue: https://homey.app/de-de/app/com.mecloud/MELCloud/test

You probably need to stop automating the app restart in case you do so.
