### ISSUE TITLE
With new version doesnt  turn off split

### ISSUE THREAD

**Issue by RDSVE** [OlivierZal/com.melcloud#525]
Hello, with the new versione of the app i cannot turn off the  split 
I can only turn on....

**Comment by OlivierZal** [comment]
Hi @RDSVE, I think I received your diagnostic by email, I answered it. Waiting for your response back 😊

**Comment by OlivierZal** [comment]
First, can you check on the device settings if the "always on" setting is turned on?

If it's off, can you please provide olivier.zalmanski@me.com with guest access from the official MELCloud mobile app or website (https://app.melcloud.com).

Thanks!

**Comment by RDSVE** [comment]
Sorry, maybe i don t understand,  i have to give you guest access to my mel cloud app account?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OlivierZal** [comment]
Feel free to confirm that "always on" is disabled in device settings and, if so, to provide me a guest access (don't worry: MELCloud app will send me an access without transmitting your credentials, and I'll remove it as soon as I've investigated).

**Comment by RDSVE** [comment]
Hi, I confirm that always  on is disabled,
I have sent to you an access to my melcloud
Thanks

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OlivierZal** [comment]
Hi @RDSVE

Thanks for the invite. From the MELCloud API perspective, I can switch on and off from Homey and it updates accordingly in MELCloud. 

So if your device remains on while switching off from Homey, that means that your physical device doesn't communicate with MELCloud API (can be a WiFi or hardware issue).

**Comment by RDSVE** [comment]
Works perfectly with "always on" disabled.
Many thanks

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
