### ISSUE TITLE
Accessing device settings crashes the Homey app

### ISSUE THREAD

**Issue by harrykantas** [OlivierZal/com.melcloud#536]
On Ecodan Air-to-water
https://github.com/user-attachments/assets/a5c2ac59-61e0-4891-9e6a-7a5524276a14

Tested on iOS
![IMG_5851](https://github.com/user-attachments/assets/5e2890d7-0357-485d-b73b-597692c5bd11)

Please do let me know if you need more info.

**Comment by OlivierZal** [comment]
Hi @harrykantas, I'll have a look.

**Comment by OlivierZal** [comment]
@harrykantas, can you please provide olivier.zalmanski@me.com with a guest access from the official MELCloud app (mobile or web https://app.melcloud.com), so I can investigate?

I cannot reproduce on my side, and I suspect a Homey issue according to the logs displayed in the video (DeviceSettingsScene is not from my code).

**Comment by OlivierZal** [comment]
@harrykantas, also it could be useful to send me the app diagnostics right after a crash, and to screenshot your device on this page: https://tools.developer.homey.app/tools/devices

**Comment by OlivierZal** [comment]
Issue from Homey seems to be confirmed: https://community.homey.app/t/intergas-incomfort-lan2rf-gateway-connection/13590/34?u=peter_kawa
