### ISSUE TITLE
Changed target temperature

### ISSUE THREAD

**Issue by Agamemnond** [OlivierZal/com.melcloud#558]
Hi, 

I'm new in the world of Homey apps and flows and I wonder how to create a flow for my Mitsubishi Ecodan that send me a push notice when the target temperature for the tank water is changed? 

I can't find any card that let me use changed target temp for the tank water or even for the tank water temp.

mfh/Torbjörn

**Comment by OlivierZal** [comment]
Hi @Agamemnond,

The cards do exist, under the "Then" cards:

![image](https://github.com/user-attachments/assets/c639df9f-184f-4cd4-988b-ba2ae10ecc98)

Sometimes you need to exit from the flows and come back again to see all the available cards (it's not handled at the app level, so I cannot fix it). 

King regards
