### ISSUE TITLE
Most info broken since 7.1.x upgrade

### ISSUE THREAD

**Issue by MTRKhn** [OlivierZal/com.melcloud#56]
No more update of flow and return temperatures, frequency and CoP since yesterday around 1PM, confirmed by my Grafana graphs :(

![47F33155-1775-4AEB-B93F-A4854AAB5E49](https://user-images.githubusercontent.com/72077818/203909787-2fdc8273-6471-4e3c-be15-7af6d20ccf2d.png)
![3A455236-51EC-4C6C-9FB4-305C704B9F6F](https://user-images.githubusercontent.com/72077818/203909821-1beed9a3-fc3b-427f-8306-570e6429fcc9.jpeg)

**Comment by MTRKhn** [comment]
Wait… looks like it’s on MELCloud side. Can someone confirm ?

**Comment by OlivierZal** [comment]
Hi @MTRKhn, I confirm that the info are still retrieved (I didn't change this part by the way).

**Comment by OlivierZal** [comment]
@MTRKhn, if you grant me an access (olivier.zalmanski@me.com) from your official MELCloud app I can check for you.

**Comment by MTRKhn** [comment]
Access granted, but i can't see any stats in MelCloud itself :(

![image](https://user-images.githubusercontent.com/72077818/203959001-65f4d54b-ff0e-4793-ad8f-2244694ce49a.png)

**Comment by OlivierZal** [comment]
@MTRKhn, here is your device seen from my Homey:

![IMG_1813](https://user-images.githubusercontent.com/88216225/203959321-0a8267ef-da45-40a0-ac6c-8b05746fc808.PNG)

**Comment by MTRKhn** [comment]
That's values from yesterday 1PM except the outdoor temperature.

**Comment by OlivierZal** [comment]
@MTRKhn, it's also what I get right now directly from the API:
```
"Device": {
    ...
    "FlowTemperature": 27.0,
    ...
    "ReturnTemperature": 25.0,
    ...
}
```

**Comment by MTRKhn** [comment]
API is dead i think lol

![image](https://user-images.githubusercontent.com/72077818/203961881-3f4e8812-d7ad-4d4a-8669-8a97ab853843.png)

Do you have access to another Air/Water PAC ?

**Comment by OlivierZal** [comment]
Yes, if there is an issue it's indeed on MELCloud API's end, not Homey / MELCloud app.

**Comment by OlivierZal** [comment]
Sorry, I think I can't help :(

**Comment by OlivierZal** [comment]
@MTRKhn, I will continue to investigate your API behaviour, don't hesitate to reach me directly to my personal email, so that I won't post here any of your personal data.

**Comment by MTRKhn** [comment]
![image](https://user-images.githubusercontent.com/72077818/203976029-0412060d-eec9-4d4c-a5ac-94fbabe12ce3.png)

**Comment by OlivierZal** [comment]
@MTRKhn 

https://twitter.com/me_europe/status/1597170377637101568?s=46&t=OuQvd4G9zxvi7uSS0Efw1A

**Comment by MTRKhn** [comment]
> @MTRKhn
> 
> https://twitter.com/me_europe/status/1597170377637101568?s=46&t=OuQvd4G9zxvi7uSS0Efw1A

Yeah I was the one leading the revolution against them lol

A full week to fix an issue on their backend. I had someone from ME France confirming that not just « a small portion » we’re affected but a lot of their customers… So now I decided to reverse engineer their Wifi appliance connectivity to gather the data locally.
