### ISSUE TITLE
Unable to add new air-to-air heatpump

### ISSUE THREAD

**Issue by oleroes** [OlivierZal/com.melcloud#579]
We had a new heat pump installed today and I have added it to my Melcloud app, but nothing happens when I trey to add it to Homey Pro 2023. I have two heat pumps and my first heat pump has been controlled by the Homey app for a couple of years now.

Homey Pro 2023 with latest firmware 
Melcloud app 40.0.0 (Got updated today before our heat pump was installed)

Regards
Ole

**Comment by oleroes** [comment]
> We had a new heat pump installed today and I have added it to my Melcloud app, but nothing happens when I trey to add it to Homey Pro 2023. I have two heat pumps and my first heat pump has been controlled by the Homey app for a couple of years now.
> 
> Homey Pro 2023 with latest firmware Melcloud app 40.0.0 (Got updated today before our heat pump was installed)
> 
> Regards Ole

Tried adding again using the Homey app on iPhone and that worked!

**Comment by OlivierZal** [comment]
I'm glad it works 😊
