### ISSUE TITLE
Problem update

### ISSUE THREAD

**Issue by FrodeAlm** [OlivierZal/com.melcloud#6]
my Hp stopped working after update. round trip water shows 22.5 degrees all the time. frequency shows 0 and gets error messages. this worked before you updated!
![9D21F974-F4A2-4A94-ADA5-271A80640DCF](https://user-images.githubusercontent.com/114644190/192954613-32fb931e-fbd3-4f3a-b58e-eb5e63a8b7df.png)
![012B68B4-9AA5-4117-BE08-7D0C50937E1D](https://user-images.githubusercontent.com/114644190/192954641-cc77049a-2ca9-4285-aeb0-be42aae7de2a.png)
![67D7BC62-3515-49E6-B1B9-5FC0DA9DA884](https://user-images.githubusercontent.com/114644190/192954646-ff863f10-b62d-4461-8839-ef5eebfb7ef7.png)
![C6ECA11B-0972-486B-BBD2-48B9E877FE38](https://user-images.githubusercontent.com/114644190/192954654-948ea8bb-7fda-4cd7-8c9a-73ea2d03e6a2.png)

**Comment by janhjordie** [comment]
@FrodeAlm can you remember what properties there were visible on the last image ? Where the frequency is in the bottom.
I know it use to show 1 or 2 rows more with data. But can't remember what it was.
I'm pretty sure it also showed the inside temperature

**Comment by OlivierZal** [comment]
Hi, I’m aware of this issue and working on it right now. Please join https://github.com/OlivierZal/com.melcloud/issues/4 to contribute and follow the resolution.

**Comment by OlivierZal** [comment]
@FrodeAlm, can you please install https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/ and test if you still have issue?

**Comment by OlivierZal** [comment]
@janhjordie, @FrodeAlm and @MTRKhn, will be solved with upcoming v3.0.6.

Don't hesitate to open a new incident for any bug you would find. 

Regards
