### ISSUE TITLE
Checking connection 

### ISSUE THREAD

**Issue by Tiwas** [OlivierZal/com.melcloud#60]
Is there a way to check the connection between the app and melcloud? Is there a set time from last login or app use when it stops functioning? My app has been acting strangely, and when I tried adding a new device my existing one came up. Still unable to turn it on and off, though...

**Comment by MTRKhn** [comment]
Problem is on Mitsubishi’s side. They screwed up their backend on Nov 25 by deploying an update and it’s slowly coming back to normal since Dec 2nd. Most of the control are still down (ON/OFF, set temp, …) are data reporting is being throttled a lot.

**Comment by Tiwas** [comment]
Thanks for replying :)

**Comment by OlivierZal** [comment]
Hi @Tiwas,

Thanks, @MTRKhn, for having replied before me :-)

Indeed, https://twitter.com/me_europe/status/1597170377637101568?s=46&t=OuQvd4G9zxvi7uSS0Efw1A
