### ISSUE TITLE
MELCloud app crashes on Homey

### ISSUE THREAD

**Issue by reidarhaver** [OlivierZal/com.melcloud#606]
Hi.
I have been controlling my Mitsubishi heatpump for years without any issues on my HomeyPro. In recent days the app tends to crash and I need to restart. This has been Going on for a few days and it crashes atleast one time every day. Any advice?

**Comment by OlivierZal** [comment]
Hi @reidarhaver,

There are discussions about this issue here: https://community.homey.app/t/app-pro-melcloud-melcloud-extension-take-control-of-your-heat-pump/73094/308

**Comment by OlivierZal** [comment]
Hi @reidarhaver, https://homey.app/en-us/app/com.mecloud/MELCloud/ should fix the issue. 

Don't hesitate to reopen the task if the issue remains.

**Comment by reidarhaver** [comment]
Great. Thank you very much.
