### ISSUE TITLE
MelCloud Crash v40.1.0

### ISSUE THREAD

**Issue by janhjordie** [OlivierZal/com.melcloud#609]
Hey Olivier
My MelCloud app suddenly can't start.
I get this error when I try restart the app

SyntaxError: /homey/user/apps/a2557cb25f0895f416b8a855fb460e32/app/app.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object._readFile (/node_modules/jsonfile/index.js:25:16)
    at async App.start (file:///app/lib/App.mjs:557:30)
    at async ManagerApps.restartApp (file:///app/lib/ManagerApps.mjs:349:9)
    
    
![image](https://github.com/user-attachments/assets/35309a95-d319-4ec1-9032-6c121bb77f77)

**Comment by OlivierZal** [comment]
Hi @janhjordie, `app.json` is not something I write but that Homey writes when installing an app. Sometimes Homey writes it wrong, what makes the app crash.

Can you please try not to restart the app but to reinstall it from https://homey.app/a/com.mecloud ?

**Comment by OlivierZal** [comment]
I'm glad it worked!
