### ISSUE TITLE
Mitsubishi Electric WSH-AP 25 air conditioner

### ISSUE THREAD

**Issue by niestadt** [OlivierZal/com.melcloud#65]
Hello, 

I am new to Homey and a few weeks ago we bought 2 air conditioners (WSH-AP 25).
I was very much looking forward to connecting these with Homey, as I had seen that there is an integration with MELcloud.
But now I see that this device is not included.
Would it be possible for you to include this device?

Can I help you with it in any way?

Kind regards, 
Dirk Niestadt

**Comment by OlivierZal** [comment]
Hi @niestadt,

Do you have a Wi-Fi module and have you configured a MELCloud account? If so you can grant me (olivier.zalmanski@me.com) a read-only access (with restricted permissions) from the official MELCloud app / website so I can see what I can do. 

Kind regards

**Comment by niestadt** [comment]
Hello Olivier,

The problem has already been solved. The login screen caused for the error, by which I was not able to connect to the MELcloud from my Homey. There was no error message but just the message that the device was not found.

I finally could log in by swiping the login screen to the top of the screen. Now I can install the 2 airco devices.

I notice though that the MELcloud does not automatically push that a temperature setting has changed.
Do you know if it is pushed only after a certain amount of time? Or should Homey every X minute check the temperature setting?

If you would like to check the devices, I can give you access.

With kind regards,
Dirk Niestadt

**Comment by OlivierZal** [comment]
Hi @niestadt, 

Indeed the login page is templated by Homey, and I agree it is not intuitive. Fortunately, login is registered and token is refreshed everyday so you won't have to enter it anymore. 

You can set device refresh interval within the settings.

Don't hesitate to tell me if you need further assistance. 

Kind regards
