### ISSUE TITLE
Installing MEL cloud for Homey

### ISSUE THREAD

**Issue by marotea001** [OlivierZal/com.melcloud#85]
I'm very interested in the Homey / MEL cloud app. I'm told it is only "Home Pro" - When I attempt to install the only option in the dropbox is Homey and the message says MEL cloud is not compatible with Homey. 

what am I doing wrong? 

![IMG_C70B70B47D21-1](https://user-images.githubusercontent.com/82568245/214875555-9ba1e703-76c8-4a2b-ab71-ab564ab1a315.jpeg)
<img width="366" alt="image" src="https://user-images.githubusercontent.com/82568245/214875673-b76b2f8b-9061-4260-ae70-317a923475f8.png">

**Comment by OlivierZal** [comment]
Hi @marotea001,

You are doing nothing wrong, as explained [here](https://github.com/OlivierZal/com.melcloud/discussions/8#discussioncomment-3759515) the MELCloud app needs to be run only on Homey Pro and cannot be run from Homey Cloud as per Homey limitation.

Sorry...

Kind regards

**Comment by marotea001** [comment]
En Français ce sera plus silmple ! :-)

Homey pro veut dire acheter un kit Homey? C’est une aussi une option pour moi car l’interface Mitsubishi / MEL est ATROCE et pas gérable.

Je suis un peu technique mais pas un programmeur.

Mille mercis.


Martin Guillaume

+33 620751457


The power of Technology and Nature for a More Sustainable World

**Comment by OlivierZal** [comment]
Oui :-)

En effet il n'y a pas d'autre choix que d'acheter la box https://homey.app/fr-fr/homey-pro/

Techniquement l'app serait tout à fait portable sur la solution Homey Cloud, il s'agit juste d'une restriction "politique"...
